# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.message_output_body import MessageOutputBody
from ..types.organization_invitation_list_response import OrganizationInvitationListResponse
from ..types.organization_invitation_response import OrganizationInvitationResponse
from ..types.organization_organization_list_response import OrganizationOrganizationListResponse
from ..types.organization_organization_member_list_response import OrganizationOrganizationMemberListResponse
from ..types.organization_organization_member_response import OrganizationOrganizationMemberResponse
from ..types.organization_organization_response import OrganizationOrganizationResponse
from .raw_client import AsyncRawOrganizationsClient, RawOrganizationsClient

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class OrganizationsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawOrganizationsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawOrganizationsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawOrganizationsClient
        """
        return self._raw_client

    def list(self, *, request_options: typing.Optional[RequestOptions] = None) -> OrganizationOrganizationListResponse:
        """
        Returns every organization the caller is a member of.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        OrganizationOrganizationListResponse
            OK

        Examples
        --------
        from axilio import AxilioApi

        client = AxilioApi(
            api_key="YOUR_API_KEY",
        )
        client.organizations.list()
        """
        _response = self._raw_client.list(request_options=request_options)
        return _response.data

    def create(
        self,
        *,
        external_org_id: str,
        name: str,
        slug: str,
        logo_url: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> OrganizationOrganizationResponse:
        """
        Creates an organization. Idempotent by the linked organization id so retries and duplicate POSTs converge. The calling user becomes the org's first admin.

        Parameters
        ----------
        external_org_id : str

        name : str

        slug : str

        logo_url : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        OrganizationOrganizationResponse
            Created

        Examples
        --------
        from axilio import AxilioApi

        client = AxilioApi(
            api_key="YOUR_API_KEY",
        )
        client.organizations.create(
            external_org_id="external_org_id",
            name="name",
            slug="slug",
        )
        """
        _response = self._raw_client.create(
            external_org_id=external_org_id, name=name, slug=slug, logo_url=logo_url, request_options=request_options
        )
        return _response.data

    def get(
        self, org_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> OrganizationOrganizationResponse:
        """
        Returns a single organization the caller is a member of.

        Parameters
        ----------
        org_id : str
            organization identifier

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        OrganizationOrganizationResponse
            OK

        Examples
        --------
        from axilio import AxilioApi

        client = AxilioApi(
            api_key="YOUR_API_KEY",
        )
        client.organizations.get(
            org_id="org_id",
        )
        """
        _response = self._raw_client.get(org_id, request_options=request_options)
        return _response.data

    def update(
        self,
        org_id: str,
        *,
        logo_url: typing.Optional[str] = OMIT,
        name: typing.Optional[str] = OMIT,
        slug: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> OrganizationOrganizationResponse:
        """
        Applies a partial update (name, slug, logo). Also marks onboarding complete the first time name or slug is set. Org admin only.

        Parameters
        ----------
        org_id : str
            organization identifier

        logo_url : typing.Optional[str]

        name : typing.Optional[str]

        slug : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        OrganizationOrganizationResponse
            OK

        Examples
        --------
        from axilio import AxilioApi

        client = AxilioApi(
            api_key="YOUR_API_KEY",
        )
        client.organizations.update(
            org_id="org_id",
        )
        """
        _response = self._raw_client.update(
            org_id, logo_url=logo_url, name=name, slug=slug, request_options=request_options
        )
        return _response.data

    def list_invitations(
        self, org_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> OrganizationInvitationListResponse:
        """
        Returns every outstanding invitation for the organization. Org admin only.

        Parameters
        ----------
        org_id : str
            organization identifier

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        OrganizationInvitationListResponse
            OK

        Examples
        --------
        from axilio import AxilioApi

        client = AxilioApi(
            api_key="YOUR_API_KEY",
        )
        client.organizations.list_invitations(
            org_id="org_id",
        )
        """
        _response = self._raw_client.list_invitations(org_id, request_options=request_options)
        return _response.data

    def create_invitation(
        self,
        org_id: str,
        *,
        email: str,
        role: str,
        redirect_url: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> OrganizationInvitationResponse:
        """
        Creates an organization invitation. Idempotent by org_id + email: rejects 409 on duplicate. Org admin only.

        Parameters
        ----------
        org_id : str
            organization identifier

        email : str

        role : str

        redirect_url : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        OrganizationInvitationResponse
            Created

        Examples
        --------
        from axilio import AxilioApi

        client = AxilioApi(
            api_key="YOUR_API_KEY",
        )
        client.organizations.create_invitation(
            org_id="org_id",
            email="email",
            role="role",
        )
        """
        _response = self._raw_client.create_invitation(
            org_id, email=email, role=role, redirect_url=redirect_url, request_options=request_options
        )
        return _response.data

    def revoke_invitation(
        self, org_id: str, invitation_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> MessageOutputBody:
        """
        Revokes an outstanding invitation and deletes the local record. Org admin only.

        Parameters
        ----------
        org_id : str
            organization identifier

        invitation_id : str
            invitation identifier

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        MessageOutputBody
            OK

        Examples
        --------
        from axilio import AxilioApi

        client = AxilioApi(
            api_key="YOUR_API_KEY",
        )
        client.organizations.revoke_invitation(
            org_id="org_id",
            invitation_id="invitation_id",
        )
        """
        _response = self._raw_client.revoke_invitation(org_id, invitation_id, request_options=request_options)
        return _response.data

    def list_members(
        self, org_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> OrganizationOrganizationMemberListResponse:
        """
        Returns every member of the organization with their role and email.

        Parameters
        ----------
        org_id : str
            organization identifier

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        OrganizationOrganizationMemberListResponse
            OK

        Examples
        --------
        from axilio import AxilioApi

        client = AxilioApi(
            api_key="YOUR_API_KEY",
        )
        client.organizations.list_members(
            org_id="org_id",
        )
        """
        _response = self._raw_client.list_members(org_id, request_options=request_options)
        return _response.data

    def add_member(
        self, org_id: str, *, role: str, user_id: str, request_options: typing.Optional[RequestOptions] = None
    ) -> OrganizationOrganizationMemberResponse:
        """
        Adds a user as a member of the organization with the given role. Idempotent: rejects 409 if the user is already a member. Org admin only.

        Parameters
        ----------
        org_id : str
            organization identifier

        role : str

        user_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        OrganizationOrganizationMemberResponse
            Created

        Examples
        --------
        from axilio import AxilioApi

        client = AxilioApi(
            api_key="YOUR_API_KEY",
        )
        client.organizations.add_member(
            org_id="org_id",
            role="role",
            user_id="user_id",
        )
        """
        _response = self._raw_client.add_member(org_id, role=role, user_id=user_id, request_options=request_options)
        return _response.data

    def remove_member(
        self, org_id: str, user_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> MessageOutputBody:
        """
        Removes a user from the organization. Rejects removing yourself, and rejects removing the last admin of an organization. Org admin only.

        Parameters
        ----------
        org_id : str
            organization identifier

        user_id : str
            user identifier to remove

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        MessageOutputBody
            OK

        Examples
        --------
        from axilio import AxilioApi

        client = AxilioApi(
            api_key="YOUR_API_KEY",
        )
        client.organizations.remove_member(
            org_id="org_id",
            user_id="user_id",
        )
        """
        _response = self._raw_client.remove_member(org_id, user_id, request_options=request_options)
        return _response.data

    def update_member_role(
        self, org_id: str, user_id: str, *, role: str, request_options: typing.Optional[RequestOptions] = None
    ) -> OrganizationOrganizationMemberResponse:
        """
        Changes a member's role. Rejects changing your own role, and rejects downgrading the last admin. Org admin only.

        Parameters
        ----------
        org_id : str
            organization identifier

        user_id : str
            user identifier whose role is being changed

        role : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        OrganizationOrganizationMemberResponse
            OK

        Examples
        --------
        from axilio import AxilioApi

        client = AxilioApi(
            api_key="YOUR_API_KEY",
        )
        client.organizations.update_member_role(
            org_id="org_id",
            user_id="user_id",
            role="role",
        )
        """
        _response = self._raw_client.update_member_role(org_id, user_id, role=role, request_options=request_options)
        return _response.data


class AsyncOrganizationsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawOrganizationsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawOrganizationsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawOrganizationsClient
        """
        return self._raw_client

    async def list(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> OrganizationOrganizationListResponse:
        """
        Returns every organization the caller is a member of.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        OrganizationOrganizationListResponse
            OK

        Examples
        --------
        import asyncio

        from axilio import AsyncAxilioApi

        client = AsyncAxilioApi(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.organizations.list()


        asyncio.run(main())
        """
        _response = await self._raw_client.list(request_options=request_options)
        return _response.data

    async def create(
        self,
        *,
        external_org_id: str,
        name: str,
        slug: str,
        logo_url: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> OrganizationOrganizationResponse:
        """
        Creates an organization. Idempotent by the linked organization id so retries and duplicate POSTs converge. The calling user becomes the org's first admin.

        Parameters
        ----------
        external_org_id : str

        name : str

        slug : str

        logo_url : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        OrganizationOrganizationResponse
            Created

        Examples
        --------
        import asyncio

        from axilio import AsyncAxilioApi

        client = AsyncAxilioApi(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.organizations.create(
                external_org_id="external_org_id",
                name="name",
                slug="slug",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create(
            external_org_id=external_org_id, name=name, slug=slug, logo_url=logo_url, request_options=request_options
        )
        return _response.data

    async def get(
        self, org_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> OrganizationOrganizationResponse:
        """
        Returns a single organization the caller is a member of.

        Parameters
        ----------
        org_id : str
            organization identifier

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        OrganizationOrganizationResponse
            OK

        Examples
        --------
        import asyncio

        from axilio import AsyncAxilioApi

        client = AsyncAxilioApi(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.organizations.get(
                org_id="org_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get(org_id, request_options=request_options)
        return _response.data

    async def update(
        self,
        org_id: str,
        *,
        logo_url: typing.Optional[str] = OMIT,
        name: typing.Optional[str] = OMIT,
        slug: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> OrganizationOrganizationResponse:
        """
        Applies a partial update (name, slug, logo). Also marks onboarding complete the first time name or slug is set. Org admin only.

        Parameters
        ----------
        org_id : str
            organization identifier

        logo_url : typing.Optional[str]

        name : typing.Optional[str]

        slug : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        OrganizationOrganizationResponse
            OK

        Examples
        --------
        import asyncio

        from axilio import AsyncAxilioApi

        client = AsyncAxilioApi(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.organizations.update(
                org_id="org_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.update(
            org_id, logo_url=logo_url, name=name, slug=slug, request_options=request_options
        )
        return _response.data

    async def list_invitations(
        self, org_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> OrganizationInvitationListResponse:
        """
        Returns every outstanding invitation for the organization. Org admin only.

        Parameters
        ----------
        org_id : str
            organization identifier

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        OrganizationInvitationListResponse
            OK

        Examples
        --------
        import asyncio

        from axilio import AsyncAxilioApi

        client = AsyncAxilioApi(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.organizations.list_invitations(
                org_id="org_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.list_invitations(org_id, request_options=request_options)
        return _response.data

    async def create_invitation(
        self,
        org_id: str,
        *,
        email: str,
        role: str,
        redirect_url: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> OrganizationInvitationResponse:
        """
        Creates an organization invitation. Idempotent by org_id + email: rejects 409 on duplicate. Org admin only.

        Parameters
        ----------
        org_id : str
            organization identifier

        email : str

        role : str

        redirect_url : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        OrganizationInvitationResponse
            Created

        Examples
        --------
        import asyncio

        from axilio import AsyncAxilioApi

        client = AsyncAxilioApi(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.organizations.create_invitation(
                org_id="org_id",
                email="email",
                role="role",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create_invitation(
            org_id, email=email, role=role, redirect_url=redirect_url, request_options=request_options
        )
        return _response.data

    async def revoke_invitation(
        self, org_id: str, invitation_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> MessageOutputBody:
        """
        Revokes an outstanding invitation and deletes the local record. Org admin only.

        Parameters
        ----------
        org_id : str
            organization identifier

        invitation_id : str
            invitation identifier

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        MessageOutputBody
            OK

        Examples
        --------
        import asyncio

        from axilio import AsyncAxilioApi

        client = AsyncAxilioApi(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.organizations.revoke_invitation(
                org_id="org_id",
                invitation_id="invitation_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.revoke_invitation(org_id, invitation_id, request_options=request_options)
        return _response.data

    async def list_members(
        self, org_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> OrganizationOrganizationMemberListResponse:
        """
        Returns every member of the organization with their role and email.

        Parameters
        ----------
        org_id : str
            organization identifier

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        OrganizationOrganizationMemberListResponse
            OK

        Examples
        --------
        import asyncio

        from axilio import AsyncAxilioApi

        client = AsyncAxilioApi(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.organizations.list_members(
                org_id="org_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.list_members(org_id, request_options=request_options)
        return _response.data

    async def add_member(
        self, org_id: str, *, role: str, user_id: str, request_options: typing.Optional[RequestOptions] = None
    ) -> OrganizationOrganizationMemberResponse:
        """
        Adds a user as a member of the organization with the given role. Idempotent: rejects 409 if the user is already a member. Org admin only.

        Parameters
        ----------
        org_id : str
            organization identifier

        role : str

        user_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        OrganizationOrganizationMemberResponse
            Created

        Examples
        --------
        import asyncio

        from axilio import AsyncAxilioApi

        client = AsyncAxilioApi(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.organizations.add_member(
                org_id="org_id",
                role="role",
                user_id="user_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.add_member(
            org_id, role=role, user_id=user_id, request_options=request_options
        )
        return _response.data

    async def remove_member(
        self, org_id: str, user_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> MessageOutputBody:
        """
        Removes a user from the organization. Rejects removing yourself, and rejects removing the last admin of an organization. Org admin only.

        Parameters
        ----------
        org_id : str
            organization identifier

        user_id : str
            user identifier to remove

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        MessageOutputBody
            OK

        Examples
        --------
        import asyncio

        from axilio import AsyncAxilioApi

        client = AsyncAxilioApi(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.organizations.remove_member(
                org_id="org_id",
                user_id="user_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.remove_member(org_id, user_id, request_options=request_options)
        return _response.data

    async def update_member_role(
        self, org_id: str, user_id: str, *, role: str, request_options: typing.Optional[RequestOptions] = None
    ) -> OrganizationOrganizationMemberResponse:
        """
        Changes a member's role. Rejects changing your own role, and rejects downgrading the last admin. Org admin only.

        Parameters
        ----------
        org_id : str
            organization identifier

        user_id : str
            user identifier whose role is being changed

        role : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        OrganizationOrganizationMemberResponse
            OK

        Examples
        --------
        import asyncio

        from axilio import AsyncAxilioApi

        client = AsyncAxilioApi(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.organizations.update_member_role(
                org_id="org_id",
                user_id="user_id",
                role="role",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.update_member_role(
            org_id, user_id, role=role, request_options=request_options
        )
        return _response.data
