# This file was auto-generated by Fern from our API Definition.

import typing
from json.decoder import JSONDecodeError

from ..core.api_error import ApiError
from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.http_response import AsyncHttpResponse, HttpResponse
from ..core.jsonable_encoder import encode_path_param
from ..core.parse_error import ParsingError
from ..core.pydantic_utilities import parse_obj_as
from ..core.request_options import RequestOptions
from ..types.message_output_body import MessageOutputBody
from ..types.organization_invitation_list_response import OrganizationInvitationListResponse
from ..types.organization_invitation_response import OrganizationInvitationResponse
from ..types.organization_organization_list_response import OrganizationOrganizationListResponse
from ..types.organization_organization_member_list_response import OrganizationOrganizationMemberListResponse
from ..types.organization_organization_member_response import OrganizationOrganizationMemberResponse
from ..types.organization_organization_response import OrganizationOrganizationResponse
from pydantic import ValidationError

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class RawOrganizationsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._client_wrapper = client_wrapper

    def list(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[OrganizationOrganizationListResponse]:
        """
        Returns every organization the caller is a member of.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[OrganizationOrganizationListResponse]
            OK
        """
        _response = self._client_wrapper.httpx_client.request(
            "organizations",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    OrganizationOrganizationListResponse,
                    parse_obj_as(
                        type_=OrganizationOrganizationListResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def create(
        self,
        *,
        external_org_id: str,
        name: str,
        slug: str,
        logo_url: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[OrganizationOrganizationResponse]:
        """
        Creates an organization. Idempotent by the linked organization id so retries and duplicate POSTs converge. The calling user becomes the org's first admin.

        Parameters
        ----------
        external_org_id : str

        name : str

        slug : str

        logo_url : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[OrganizationOrganizationResponse]
            Created
        """
        _response = self._client_wrapper.httpx_client.request(
            "organizations",
            method="POST",
            json={
                "external_org_id": external_org_id,
                "logo_url": logo_url,
                "name": name,
                "slug": slug,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    OrganizationOrganizationResponse,
                    parse_obj_as(
                        type_=OrganizationOrganizationResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def get(
        self, org_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[OrganizationOrganizationResponse]:
        """
        Returns a single organization the caller is a member of.

        Parameters
        ----------
        org_id : str
            organization identifier

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[OrganizationOrganizationResponse]
            OK
        """
        _response = self._client_wrapper.httpx_client.request(
            f"organizations/{encode_path_param(org_id)}",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    OrganizationOrganizationResponse,
                    parse_obj_as(
                        type_=OrganizationOrganizationResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def update(
        self,
        org_id: str,
        *,
        logo_url: typing.Optional[str] = OMIT,
        name: typing.Optional[str] = OMIT,
        slug: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[OrganizationOrganizationResponse]:
        """
        Applies a partial update (name, slug, logo). Also marks onboarding complete the first time name or slug is set. Org admin only.

        Parameters
        ----------
        org_id : str
            organization identifier

        logo_url : typing.Optional[str]

        name : typing.Optional[str]

        slug : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[OrganizationOrganizationResponse]
            OK
        """
        _response = self._client_wrapper.httpx_client.request(
            f"organizations/{encode_path_param(org_id)}",
            method="PATCH",
            json={
                "logo_url": logo_url,
                "name": name,
                "slug": slug,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    OrganizationOrganizationResponse,
                    parse_obj_as(
                        type_=OrganizationOrganizationResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def list_invitations(
        self, org_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[OrganizationInvitationListResponse]:
        """
        Returns every outstanding invitation for the organization. Org admin only.

        Parameters
        ----------
        org_id : str
            organization identifier

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[OrganizationInvitationListResponse]
            OK
        """
        _response = self._client_wrapper.httpx_client.request(
            f"organizations/{encode_path_param(org_id)}/invitations",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    OrganizationInvitationListResponse,
                    parse_obj_as(
                        type_=OrganizationInvitationListResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def create_invitation(
        self,
        org_id: str,
        *,
        email: str,
        role: str,
        redirect_url: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[OrganizationInvitationResponse]:
        """
        Creates an organization invitation. Idempotent by org_id + email: rejects 409 on duplicate. Org admin only.

        Parameters
        ----------
        org_id : str
            organization identifier

        email : str

        role : str

        redirect_url : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[OrganizationInvitationResponse]
            Created
        """
        _response = self._client_wrapper.httpx_client.request(
            f"organizations/{encode_path_param(org_id)}/invitations",
            method="POST",
            json={
                "email": email,
                "redirect_url": redirect_url,
                "role": role,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    OrganizationInvitationResponse,
                    parse_obj_as(
                        type_=OrganizationInvitationResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def revoke_invitation(
        self, org_id: str, invitation_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[MessageOutputBody]:
        """
        Revokes an outstanding invitation and deletes the local record. Org admin only.

        Parameters
        ----------
        org_id : str
            organization identifier

        invitation_id : str
            invitation identifier

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[MessageOutputBody]
            OK
        """
        _response = self._client_wrapper.httpx_client.request(
            f"organizations/{encode_path_param(org_id)}/invitations/{encode_path_param(invitation_id)}",
            method="DELETE",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    MessageOutputBody,
                    parse_obj_as(
                        type_=MessageOutputBody,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def list_members(
        self, org_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[OrganizationOrganizationMemberListResponse]:
        """
        Returns every member of the organization with their role and email.

        Parameters
        ----------
        org_id : str
            organization identifier

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[OrganizationOrganizationMemberListResponse]
            OK
        """
        _response = self._client_wrapper.httpx_client.request(
            f"organizations/{encode_path_param(org_id)}/members",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    OrganizationOrganizationMemberListResponse,
                    parse_obj_as(
                        type_=OrganizationOrganizationMemberListResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def add_member(
        self, org_id: str, *, role: str, user_id: str, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[OrganizationOrganizationMemberResponse]:
        """
        Adds a user as a member of the organization with the given role. Idempotent: rejects 409 if the user is already a member. Org admin only.

        Parameters
        ----------
        org_id : str
            organization identifier

        role : str

        user_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[OrganizationOrganizationMemberResponse]
            Created
        """
        _response = self._client_wrapper.httpx_client.request(
            f"organizations/{encode_path_param(org_id)}/members",
            method="POST",
            json={
                "role": role,
                "user_id": user_id,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    OrganizationOrganizationMemberResponse,
                    parse_obj_as(
                        type_=OrganizationOrganizationMemberResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def remove_member(
        self, org_id: str, user_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[MessageOutputBody]:
        """
        Removes a user from the organization. Rejects removing yourself, and rejects removing the last admin of an organization. Org admin only.

        Parameters
        ----------
        org_id : str
            organization identifier

        user_id : str
            user identifier to remove

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[MessageOutputBody]
            OK
        """
        _response = self._client_wrapper.httpx_client.request(
            f"organizations/{encode_path_param(org_id)}/members/{encode_path_param(user_id)}",
            method="DELETE",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    MessageOutputBody,
                    parse_obj_as(
                        type_=MessageOutputBody,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def update_member_role(
        self, org_id: str, user_id: str, *, role: str, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[OrganizationOrganizationMemberResponse]:
        """
        Changes a member's role. Rejects changing your own role, and rejects downgrading the last admin. Org admin only.

        Parameters
        ----------
        org_id : str
            organization identifier

        user_id : str
            user identifier whose role is being changed

        role : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[OrganizationOrganizationMemberResponse]
            OK
        """
        _response = self._client_wrapper.httpx_client.request(
            f"organizations/{encode_path_param(org_id)}/members/{encode_path_param(user_id)}",
            method="PATCH",
            json={
                "role": role,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    OrganizationOrganizationMemberResponse,
                    parse_obj_as(
                        type_=OrganizationOrganizationMemberResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)


class AsyncRawOrganizationsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._client_wrapper = client_wrapper

    async def list(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[OrganizationOrganizationListResponse]:
        """
        Returns every organization the caller is a member of.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[OrganizationOrganizationListResponse]
            OK
        """
        _response = await self._client_wrapper.httpx_client.request(
            "organizations",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    OrganizationOrganizationListResponse,
                    parse_obj_as(
                        type_=OrganizationOrganizationListResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def create(
        self,
        *,
        external_org_id: str,
        name: str,
        slug: str,
        logo_url: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[OrganizationOrganizationResponse]:
        """
        Creates an organization. Idempotent by the linked organization id so retries and duplicate POSTs converge. The calling user becomes the org's first admin.

        Parameters
        ----------
        external_org_id : str

        name : str

        slug : str

        logo_url : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[OrganizationOrganizationResponse]
            Created
        """
        _response = await self._client_wrapper.httpx_client.request(
            "organizations",
            method="POST",
            json={
                "external_org_id": external_org_id,
                "logo_url": logo_url,
                "name": name,
                "slug": slug,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    OrganizationOrganizationResponse,
                    parse_obj_as(
                        type_=OrganizationOrganizationResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def get(
        self, org_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[OrganizationOrganizationResponse]:
        """
        Returns a single organization the caller is a member of.

        Parameters
        ----------
        org_id : str
            organization identifier

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[OrganizationOrganizationResponse]
            OK
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"organizations/{encode_path_param(org_id)}",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    OrganizationOrganizationResponse,
                    parse_obj_as(
                        type_=OrganizationOrganizationResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def update(
        self,
        org_id: str,
        *,
        logo_url: typing.Optional[str] = OMIT,
        name: typing.Optional[str] = OMIT,
        slug: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[OrganizationOrganizationResponse]:
        """
        Applies a partial update (name, slug, logo). Also marks onboarding complete the first time name or slug is set. Org admin only.

        Parameters
        ----------
        org_id : str
            organization identifier

        logo_url : typing.Optional[str]

        name : typing.Optional[str]

        slug : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[OrganizationOrganizationResponse]
            OK
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"organizations/{encode_path_param(org_id)}",
            method="PATCH",
            json={
                "logo_url": logo_url,
                "name": name,
                "slug": slug,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    OrganizationOrganizationResponse,
                    parse_obj_as(
                        type_=OrganizationOrganizationResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def list_invitations(
        self, org_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[OrganizationInvitationListResponse]:
        """
        Returns every outstanding invitation for the organization. Org admin only.

        Parameters
        ----------
        org_id : str
            organization identifier

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[OrganizationInvitationListResponse]
            OK
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"organizations/{encode_path_param(org_id)}/invitations",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    OrganizationInvitationListResponse,
                    parse_obj_as(
                        type_=OrganizationInvitationListResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def create_invitation(
        self,
        org_id: str,
        *,
        email: str,
        role: str,
        redirect_url: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[OrganizationInvitationResponse]:
        """
        Creates an organization invitation. Idempotent by org_id + email: rejects 409 on duplicate. Org admin only.

        Parameters
        ----------
        org_id : str
            organization identifier

        email : str

        role : str

        redirect_url : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[OrganizationInvitationResponse]
            Created
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"organizations/{encode_path_param(org_id)}/invitations",
            method="POST",
            json={
                "email": email,
                "redirect_url": redirect_url,
                "role": role,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    OrganizationInvitationResponse,
                    parse_obj_as(
                        type_=OrganizationInvitationResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def revoke_invitation(
        self, org_id: str, invitation_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[MessageOutputBody]:
        """
        Revokes an outstanding invitation and deletes the local record. Org admin only.

        Parameters
        ----------
        org_id : str
            organization identifier

        invitation_id : str
            invitation identifier

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[MessageOutputBody]
            OK
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"organizations/{encode_path_param(org_id)}/invitations/{encode_path_param(invitation_id)}",
            method="DELETE",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    MessageOutputBody,
                    parse_obj_as(
                        type_=MessageOutputBody,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def list_members(
        self, org_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[OrganizationOrganizationMemberListResponse]:
        """
        Returns every member of the organization with their role and email.

        Parameters
        ----------
        org_id : str
            organization identifier

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[OrganizationOrganizationMemberListResponse]
            OK
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"organizations/{encode_path_param(org_id)}/members",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    OrganizationOrganizationMemberListResponse,
                    parse_obj_as(
                        type_=OrganizationOrganizationMemberListResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def add_member(
        self, org_id: str, *, role: str, user_id: str, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[OrganizationOrganizationMemberResponse]:
        """
        Adds a user as a member of the organization with the given role. Idempotent: rejects 409 if the user is already a member. Org admin only.

        Parameters
        ----------
        org_id : str
            organization identifier

        role : str

        user_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[OrganizationOrganizationMemberResponse]
            Created
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"organizations/{encode_path_param(org_id)}/members",
            method="POST",
            json={
                "role": role,
                "user_id": user_id,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    OrganizationOrganizationMemberResponse,
                    parse_obj_as(
                        type_=OrganizationOrganizationMemberResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def remove_member(
        self, org_id: str, user_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[MessageOutputBody]:
        """
        Removes a user from the organization. Rejects removing yourself, and rejects removing the last admin of an organization. Org admin only.

        Parameters
        ----------
        org_id : str
            organization identifier

        user_id : str
            user identifier to remove

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[MessageOutputBody]
            OK
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"organizations/{encode_path_param(org_id)}/members/{encode_path_param(user_id)}",
            method="DELETE",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    MessageOutputBody,
                    parse_obj_as(
                        type_=MessageOutputBody,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def update_member_role(
        self, org_id: str, user_id: str, *, role: str, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[OrganizationOrganizationMemberResponse]:
        """
        Changes a member's role. Rejects changing your own role, and rejects downgrading the last admin. Org admin only.

        Parameters
        ----------
        org_id : str
            organization identifier

        user_id : str
            user identifier whose role is being changed

        role : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[OrganizationOrganizationMemberResponse]
            OK
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"organizations/{encode_path_param(org_id)}/members/{encode_path_param(user_id)}",
            method="PATCH",
            json={
                "role": role,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    OrganizationOrganizationMemberResponse,
                    parse_obj_as(
                        type_=OrganizationOrganizationMemberResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)
