# This file was auto-generated by Fern from our API Definition.

import typing
from json.decoder import JSONDecodeError

from ..core.api_error import ApiError
from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.http_response import AsyncHttpResponse, HttpResponse
from ..core.jsonable_encoder import encode_path_param
from ..core.parse_error import ParsingError
from ..core.pydantic_utilities import parse_obj_as
from ..core.request_options import RequestOptions
from ..types.message_output_body import MessageOutputBody
from ..types.workflow_create_response import WorkflowCreateResponse
from ..types.workflow_get_code_response import WorkflowGetCodeResponse
from ..types.workflow_list_response import WorkflowListResponse
from ..types.workflow_list_revisions_response import WorkflowListRevisionsResponse
from ..types.workflow_response import WorkflowResponse
from ..types.workflow_revision_detail import WorkflowRevisionDetail
from ..types.workflow_save_code_response import WorkflowSaveCodeResponse
from .types.workflow_create_request_ocr_engine import WorkflowCreateRequestOcrEngine
from .types.workflow_create_request_platform import WorkflowCreateRequestPlatform
from .types.workflow_update_request_ocr_engine import WorkflowUpdateRequestOcrEngine
from .types.workflow_update_request_platform import WorkflowUpdateRequestPlatform
from .types.workflow_update_request_status import WorkflowUpdateRequestStatus
from pydantic import ValidationError

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class RawWorkflowsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._client_wrapper = client_wrapper

    def list(
        self,
        *,
        limit: typing.Optional[int] = None,
        offset: typing.Optional[int] = None,
        search: typing.Optional[str] = None,
        status: typing.Optional[typing.Sequence[str]] = None,
        platform: typing.Optional[typing.Sequence[str]] = None,
        created_after: typing.Optional[str] = None,
        created_before: typing.Optional[str] = None,
        last_run_after: typing.Optional[str] = None,
        last_run_before: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[WorkflowListResponse]:
        """
        Paginated list of workflows in the caller's org, with optional search, status, platform, and created/last-run date filters via query params.

        Parameters
        ----------
        limit : typing.Optional[int]

        offset : typing.Optional[int]

        search : typing.Optional[str]
            free-text search across workflow name or ID substring

        status : typing.Optional[typing.Sequence[str]]
            filter by workflow status (lowercase)

        platform : typing.Optional[typing.Sequence[str]]
            filter by device platform (lowercase)

        created_after : typing.Optional[str]
            only workflows created at/after this RFC3339 time

        created_before : typing.Optional[str]
            only workflows created at/before this RFC3339 time

        last_run_after : typing.Optional[str]
            only workflows last run at/after this RFC3339 time

        last_run_before : typing.Optional[str]
            only workflows last run at/before this RFC3339 time

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[WorkflowListResponse]
            OK
        """
        _response = self._client_wrapper.httpx_client.request(
            "workflows",
            method="GET",
            params={
                "limit": limit,
                "offset": offset,
                "search": search,
                "status": status,
                "platform": platform,
                "created_after": created_after,
                "created_before": created_before,
                "last_run_after": last_run_after,
                "last_run_before": last_run_before,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    WorkflowListResponse,
                    parse_obj_as(
                        type_=WorkflowListResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def create(
        self,
        *,
        name: str,
        code: typing.Optional[str] = OMIT,
        ocr_engine: typing.Optional[WorkflowCreateRequestOcrEngine] = OMIT,
        platform: typing.Optional[WorkflowCreateRequestPlatform] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[WorkflowCreateResponse]:
        """
        Creates a workflow in the caller's org. Name must match ^[A-Za-z0-9_-]+$ and be unique within the org. Pass code to save the workflow's first code revision atomically with it; omit it to create an empty workflow and add code later. Returns the workflow_id (plus revision_id and revision when code was provided).

        Parameters
        ----------
        name : str
            Human-readable workflow name.

        code : typing.Optional[str]
            Optional Python source for the workflow's first revision, saved atomically with the workflow when provided.

        ocr_engine : typing.Optional[WorkflowCreateRequestOcrEngine]
            OCR backend to use.

        platform : typing.Optional[WorkflowCreateRequestPlatform]
            Target OS platform.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[WorkflowCreateResponse]
            Created
        """
        _response = self._client_wrapper.httpx_client.request(
            "workflows",
            method="POST",
            json={
                "code": code,
                "name": name,
                "ocr_engine": ocr_engine,
                "platform": platform,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    WorkflowCreateResponse,
                    parse_obj_as(
                        type_=WorkflowCreateResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def get(
        self, workflow_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[WorkflowResponse]:
        """
        Returns a single workflow, scoped to the caller's org (workflows in other orgs return 404).

        Parameters
        ----------
        workflow_id : str
            workflow identifier

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[WorkflowResponse]
            OK
        """
        _response = self._client_wrapper.httpx_client.request(
            f"workflows/{encode_path_param(workflow_id)}",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    WorkflowResponse,
                    parse_obj_as(
                        type_=WorkflowResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def update(
        self,
        workflow_id: str,
        *,
        name: typing.Optional[str] = OMIT,
        ocr_engine: typing.Optional[WorkflowUpdateRequestOcrEngine] = OMIT,
        platform: typing.Optional[WorkflowUpdateRequestPlatform] = OMIT,
        status: typing.Optional[WorkflowUpdateRequestStatus] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[WorkflowResponse]:
        """
        Applies a partial update (name, platform, status, ocr_engine). Org-scoped — workflows in other orgs return 404.

        Parameters
        ----------
        workflow_id : str
            workflow identifier

        name : typing.Optional[str]
            Updated workflow name.

        ocr_engine : typing.Optional[WorkflowUpdateRequestOcrEngine]
            Updated OCR backend selection.

        platform : typing.Optional[WorkflowUpdateRequestPlatform]
            Updated target platform.

        status : typing.Optional[WorkflowUpdateRequestStatus]
            Updated lifecycle status.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[WorkflowResponse]
            OK
        """
        _response = self._client_wrapper.httpx_client.request(
            f"workflows/{encode_path_param(workflow_id)}",
            method="PUT",
            json={
                "name": name,
                "ocr_engine": ocr_engine,
                "platform": platform,
                "status": status,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    WorkflowResponse,
                    parse_obj_as(
                        type_=WorkflowResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def delete(
        self, workflow_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[MessageOutputBody]:
        """
        Deletes a workflow. Org-scoped — workflows in other orgs return 404.

        Parameters
        ----------
        workflow_id : str
            workflow identifier

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[MessageOutputBody]
            OK
        """
        _response = self._client_wrapper.httpx_client.request(
            f"workflows/{encode_path_param(workflow_id)}",
            method="DELETE",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    MessageOutputBody,
                    parse_obj_as(
                        type_=MessageOutputBody,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def get_code(
        self, workflow_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[WorkflowGetCodeResponse]:
        """
        Returns the source code of the workflow's current revision, scoped to the caller's org.

        Parameters
        ----------
        workflow_id : str
            workflow identifier

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[WorkflowGetCodeResponse]
            OK
        """
        _response = self._client_wrapper.httpx_client.request(
            f"workflows/{encode_path_param(workflow_id)}/code",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    WorkflowGetCodeResponse,
                    parse_obj_as(
                        type_=WorkflowGetCodeResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def save_code(
        self,
        workflow_id: str,
        *,
        source: str,
        message: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[WorkflowSaveCodeResponse]:
        """
        Persists a new revision of the workflow's code. Hash-deduplicates against the current revision (no-op if unchanged). Source is capped at 256KB.

        Parameters
        ----------
        workflow_id : str
            workflow identifier

        source : str
            Python source the user typed.

        message : typing.Optional[str]
            Optional commit-style note.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[WorkflowSaveCodeResponse]
            OK
        """
        _response = self._client_wrapper.httpx_client.request(
            f"workflows/{encode_path_param(workflow_id)}/code",
            method="POST",
            json={
                "message": message,
                "source": source,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    WorkflowSaveCodeResponse,
                    parse_obj_as(
                        type_=WorkflowSaveCodeResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def restore_revision(
        self, workflow_id: str, *, revision_id: str, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[WorkflowSaveCodeResponse]:
        """
        Creates a new revision with the source of the named revision. Does NOT dedup against the current revision so the action is auditable in the revision history.

        Parameters
        ----------
        workflow_id : str
            workflow identifier

        revision_id : str
            Revision to restore.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[WorkflowSaveCodeResponse]
            OK
        """
        _response = self._client_wrapper.httpx_client.request(
            f"workflows/{encode_path_param(workflow_id)}/code/restore",
            method="POST",
            json={
                "revision_id": revision_id,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    WorkflowSaveCodeResponse,
                    parse_obj_as(
                        type_=WorkflowSaveCodeResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def list_revisions(
        self,
        workflow_id: str,
        *,
        limit: typing.Optional[int] = None,
        before: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[WorkflowListRevisionsResponse]:
        """
        Returns revision metadata (id, number, author, message, bytes, sha256, created_at) for the workflow, in reverse-chronological order. Use the `before` cursor to paginate older revisions.

        Parameters
        ----------
        workflow_id : str
            workflow identifier

        limit : typing.Optional[int]

        before : typing.Optional[int]
            cursor: return revisions older than this revision number

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[WorkflowListRevisionsResponse]
            OK
        """
        _response = self._client_wrapper.httpx_client.request(
            f"workflows/{encode_path_param(workflow_id)}/revisions",
            method="GET",
            params={
                "limit": limit,
                "before": before,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    WorkflowListRevisionsResponse,
                    parse_obj_as(
                        type_=WorkflowListRevisionsResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def get_revision(
        self, workflow_id: str, revision_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[WorkflowRevisionDetail]:
        """
        Returns a single revision including its full source. Defense-in-depth: the revision must belong to the named workflow or it's treated as missing.

        Parameters
        ----------
        workflow_id : str
            workflow identifier

        revision_id : str
            revision identifier

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[WorkflowRevisionDetail]
            OK
        """
        _response = self._client_wrapper.httpx_client.request(
            f"workflows/{encode_path_param(workflow_id)}/revisions/{encode_path_param(revision_id)}",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    WorkflowRevisionDetail,
                    parse_obj_as(
                        type_=WorkflowRevisionDetail,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)


class AsyncRawWorkflowsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._client_wrapper = client_wrapper

    async def list(
        self,
        *,
        limit: typing.Optional[int] = None,
        offset: typing.Optional[int] = None,
        search: typing.Optional[str] = None,
        status: typing.Optional[typing.Sequence[str]] = None,
        platform: typing.Optional[typing.Sequence[str]] = None,
        created_after: typing.Optional[str] = None,
        created_before: typing.Optional[str] = None,
        last_run_after: typing.Optional[str] = None,
        last_run_before: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[WorkflowListResponse]:
        """
        Paginated list of workflows in the caller's org, with optional search, status, platform, and created/last-run date filters via query params.

        Parameters
        ----------
        limit : typing.Optional[int]

        offset : typing.Optional[int]

        search : typing.Optional[str]
            free-text search across workflow name or ID substring

        status : typing.Optional[typing.Sequence[str]]
            filter by workflow status (lowercase)

        platform : typing.Optional[typing.Sequence[str]]
            filter by device platform (lowercase)

        created_after : typing.Optional[str]
            only workflows created at/after this RFC3339 time

        created_before : typing.Optional[str]
            only workflows created at/before this RFC3339 time

        last_run_after : typing.Optional[str]
            only workflows last run at/after this RFC3339 time

        last_run_before : typing.Optional[str]
            only workflows last run at/before this RFC3339 time

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[WorkflowListResponse]
            OK
        """
        _response = await self._client_wrapper.httpx_client.request(
            "workflows",
            method="GET",
            params={
                "limit": limit,
                "offset": offset,
                "search": search,
                "status": status,
                "platform": platform,
                "created_after": created_after,
                "created_before": created_before,
                "last_run_after": last_run_after,
                "last_run_before": last_run_before,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    WorkflowListResponse,
                    parse_obj_as(
                        type_=WorkflowListResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def create(
        self,
        *,
        name: str,
        code: typing.Optional[str] = OMIT,
        ocr_engine: typing.Optional[WorkflowCreateRequestOcrEngine] = OMIT,
        platform: typing.Optional[WorkflowCreateRequestPlatform] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[WorkflowCreateResponse]:
        """
        Creates a workflow in the caller's org. Name must match ^[A-Za-z0-9_-]+$ and be unique within the org. Pass code to save the workflow's first code revision atomically with it; omit it to create an empty workflow and add code later. Returns the workflow_id (plus revision_id and revision when code was provided).

        Parameters
        ----------
        name : str
            Human-readable workflow name.

        code : typing.Optional[str]
            Optional Python source for the workflow's first revision, saved atomically with the workflow when provided.

        ocr_engine : typing.Optional[WorkflowCreateRequestOcrEngine]
            OCR backend to use.

        platform : typing.Optional[WorkflowCreateRequestPlatform]
            Target OS platform.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[WorkflowCreateResponse]
            Created
        """
        _response = await self._client_wrapper.httpx_client.request(
            "workflows",
            method="POST",
            json={
                "code": code,
                "name": name,
                "ocr_engine": ocr_engine,
                "platform": platform,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    WorkflowCreateResponse,
                    parse_obj_as(
                        type_=WorkflowCreateResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def get(
        self, workflow_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[WorkflowResponse]:
        """
        Returns a single workflow, scoped to the caller's org (workflows in other orgs return 404).

        Parameters
        ----------
        workflow_id : str
            workflow identifier

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[WorkflowResponse]
            OK
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"workflows/{encode_path_param(workflow_id)}",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    WorkflowResponse,
                    parse_obj_as(
                        type_=WorkflowResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def update(
        self,
        workflow_id: str,
        *,
        name: typing.Optional[str] = OMIT,
        ocr_engine: typing.Optional[WorkflowUpdateRequestOcrEngine] = OMIT,
        platform: typing.Optional[WorkflowUpdateRequestPlatform] = OMIT,
        status: typing.Optional[WorkflowUpdateRequestStatus] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[WorkflowResponse]:
        """
        Applies a partial update (name, platform, status, ocr_engine). Org-scoped — workflows in other orgs return 404.

        Parameters
        ----------
        workflow_id : str
            workflow identifier

        name : typing.Optional[str]
            Updated workflow name.

        ocr_engine : typing.Optional[WorkflowUpdateRequestOcrEngine]
            Updated OCR backend selection.

        platform : typing.Optional[WorkflowUpdateRequestPlatform]
            Updated target platform.

        status : typing.Optional[WorkflowUpdateRequestStatus]
            Updated lifecycle status.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[WorkflowResponse]
            OK
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"workflows/{encode_path_param(workflow_id)}",
            method="PUT",
            json={
                "name": name,
                "ocr_engine": ocr_engine,
                "platform": platform,
                "status": status,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    WorkflowResponse,
                    parse_obj_as(
                        type_=WorkflowResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def delete(
        self, workflow_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[MessageOutputBody]:
        """
        Deletes a workflow. Org-scoped — workflows in other orgs return 404.

        Parameters
        ----------
        workflow_id : str
            workflow identifier

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[MessageOutputBody]
            OK
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"workflows/{encode_path_param(workflow_id)}",
            method="DELETE",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    MessageOutputBody,
                    parse_obj_as(
                        type_=MessageOutputBody,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def get_code(
        self, workflow_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[WorkflowGetCodeResponse]:
        """
        Returns the source code of the workflow's current revision, scoped to the caller's org.

        Parameters
        ----------
        workflow_id : str
            workflow identifier

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[WorkflowGetCodeResponse]
            OK
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"workflows/{encode_path_param(workflow_id)}/code",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    WorkflowGetCodeResponse,
                    parse_obj_as(
                        type_=WorkflowGetCodeResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def save_code(
        self,
        workflow_id: str,
        *,
        source: str,
        message: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[WorkflowSaveCodeResponse]:
        """
        Persists a new revision of the workflow's code. Hash-deduplicates against the current revision (no-op if unchanged). Source is capped at 256KB.

        Parameters
        ----------
        workflow_id : str
            workflow identifier

        source : str
            Python source the user typed.

        message : typing.Optional[str]
            Optional commit-style note.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[WorkflowSaveCodeResponse]
            OK
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"workflows/{encode_path_param(workflow_id)}/code",
            method="POST",
            json={
                "message": message,
                "source": source,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    WorkflowSaveCodeResponse,
                    parse_obj_as(
                        type_=WorkflowSaveCodeResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def restore_revision(
        self, workflow_id: str, *, revision_id: str, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[WorkflowSaveCodeResponse]:
        """
        Creates a new revision with the source of the named revision. Does NOT dedup against the current revision so the action is auditable in the revision history.

        Parameters
        ----------
        workflow_id : str
            workflow identifier

        revision_id : str
            Revision to restore.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[WorkflowSaveCodeResponse]
            OK
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"workflows/{encode_path_param(workflow_id)}/code/restore",
            method="POST",
            json={
                "revision_id": revision_id,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    WorkflowSaveCodeResponse,
                    parse_obj_as(
                        type_=WorkflowSaveCodeResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def list_revisions(
        self,
        workflow_id: str,
        *,
        limit: typing.Optional[int] = None,
        before: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[WorkflowListRevisionsResponse]:
        """
        Returns revision metadata (id, number, author, message, bytes, sha256, created_at) for the workflow, in reverse-chronological order. Use the `before` cursor to paginate older revisions.

        Parameters
        ----------
        workflow_id : str
            workflow identifier

        limit : typing.Optional[int]

        before : typing.Optional[int]
            cursor: return revisions older than this revision number

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[WorkflowListRevisionsResponse]
            OK
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"workflows/{encode_path_param(workflow_id)}/revisions",
            method="GET",
            params={
                "limit": limit,
                "before": before,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    WorkflowListRevisionsResponse,
                    parse_obj_as(
                        type_=WorkflowListRevisionsResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def get_revision(
        self, workflow_id: str, revision_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[WorkflowRevisionDetail]:
        """
        Returns a single revision including its full source. Defense-in-depth: the revision must belong to the named workflow or it's treated as missing.

        Parameters
        ----------
        workflow_id : str
            workflow identifier

        revision_id : str
            revision identifier

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[WorkflowRevisionDetail]
            OK
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"workflows/{encode_path_param(workflow_id)}/revisions/{encode_path_param(revision_id)}",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    WorkflowRevisionDetail,
                    parse_obj_as(
                        type_=WorkflowRevisionDetail,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)
