# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.delete_file_output_body import DeleteFileOutputBody
from ..types.file_download_list_response import FileDownloadListResponse
from .raw_client import AsyncRawDownloadsClient, RawDownloadsClient
from .types.downloads_list_request_order import DownloadsListRequestOrder
from .types.downloads_list_request_sort import DownloadsListRequestSort


class DownloadsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawDownloadsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawDownloadsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawDownloadsClient
        """
        return self._raw_client

    def list(
        self,
        *,
        q: typing.Optional[str] = None,
        mime_type: typing.Optional[str] = None,
        min_size_bytes: typing.Optional[int] = None,
        max_size_bytes: typing.Optional[int] = None,
        created_after: typing.Optional[dt.datetime] = None,
        created_before: typing.Optional[dt.datetime] = None,
        limit: typing.Optional[int] = None,
        offset: typing.Optional[int] = None,
        session_id: typing.Optional[str] = None,
        sort: typing.Optional[DownloadsListRequestSort] = None,
        order: typing.Optional[DownloadsListRequestOrder] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> FileDownloadListResponse:
        """
        Returns one page of the files captured off phones during sessions (AXI-1449), newest first. Each row carries its capture state: a skipped or failed capture is a visible entry with a reason, not an absence. Downloads share the library and its storage quota with uploads, and a ready download can be delivered to a phone by its id like any upload.

        Parameters
        ----------
        q : typing.Optional[str]
            filter by filename, case-insensitive substring match

        mime_type : typing.Optional[str]
            only downloads of exactly this media type

        min_size_bytes : typing.Optional[int]
            only downloads at least this many bytes (0 = no bound)

        max_size_bytes : typing.Optional[int]
            only downloads at most this many bytes (0 = no bound)

        created_after : typing.Optional[dt.datetime]
            only downloads registered at or after this time (RFC 3339)

        created_before : typing.Optional[dt.datetime]
            only downloads registered at or before this time (RFC 3339)

        limit : typing.Optional[int]
            max items per page

        offset : typing.Optional[int]
            pagination offset

        session_id : typing.Optional[str]
            only downloads captured by this session

        sort : typing.Optional[DownloadsListRequestSort]
            field to sort by

        order : typing.Optional[DownloadsListRequestOrder]
            sort direction

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        FileDownloadListResponse
            OK

        Examples
        --------
        from axilio import AxilioApi

        client = AxilioApi(
            api_key="YOUR_API_KEY",
        )
        client.downloads.list()
        """
        _response = self._raw_client.list(
            q=q,
            mime_type=mime_type,
            min_size_bytes=min_size_bytes,
            max_size_bytes=max_size_bytes,
            created_after=created_after,
            created_before=created_before,
            limit=limit,
            offset=offset,
            session_id=session_id,
            sort=sort,
            order=order,
            request_options=request_options,
        )
        return _response.data

    def delete(
        self, download_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> DeleteFileOutputBody:
        """
        Removes a captured file from the org's library and everywhere it was delivered: the stored object and the library entry go immediately, and every phone the file was pushed to is scheduled to remove its copy (removal is confirmed per phone and retried until it lands), the same recall an upload's delete runs. The response reports how many phones that recall reaches. The source phone's own copy from the capture session is outside the recall: it belongs to the session, not the library.

        Parameters
        ----------
        download_id : str
            download identifier to delete

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        DeleteFileOutputBody
            OK

        Examples
        --------
        from axilio import AxilioApi

        client = AxilioApi(
            api_key="YOUR_API_KEY",
        )
        client.downloads.delete(
            download_id="download_id",
        )
        """
        _response = self._raw_client.delete(download_id, request_options=request_options)
        return _response.data

    def phones_session_downloads(
        self,
        session_id: str,
        *,
        q: typing.Optional[str] = None,
        mime_type: typing.Optional[str] = None,
        min_size_bytes: typing.Optional[int] = None,
        max_size_bytes: typing.Optional[int] = None,
        created_after: typing.Optional[dt.datetime] = None,
        created_before: typing.Optional[dt.datetime] = None,
        limit: typing.Optional[int] = None,
        offset: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> FileDownloadListResponse:
        """
        Returns the files this session captured off its phone, newest first — the direct answer to "what did this session download". Rows appear at detection, before the bytes finish moving, so a caller waiting on a file watches its capture state progress rather than an empty list.

        Parameters
        ----------
        session_id : str
            session whose captures to list

        q : typing.Optional[str]
            filter by filename, case-insensitive substring match

        mime_type : typing.Optional[str]
            only downloads of exactly this media type

        min_size_bytes : typing.Optional[int]
            only downloads at least this many bytes (0 = no bound)

        max_size_bytes : typing.Optional[int]
            only downloads at most this many bytes (0 = no bound)

        created_after : typing.Optional[dt.datetime]
            only downloads registered at or after this time (RFC 3339)

        created_before : typing.Optional[dt.datetime]
            only downloads registered at or before this time (RFC 3339)

        limit : typing.Optional[int]
            max items per page

        offset : typing.Optional[int]
            pagination offset

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        FileDownloadListResponse
            OK

        Examples
        --------
        from axilio import AxilioApi

        client = AxilioApi(
            api_key="YOUR_API_KEY",
        )
        client.downloads.phones_session_downloads(
            session_id="session_id",
        )
        """
        _response = self._raw_client.phones_session_downloads(
            session_id,
            q=q,
            mime_type=mime_type,
            min_size_bytes=min_size_bytes,
            max_size_bytes=max_size_bytes,
            created_after=created_after,
            created_before=created_before,
            limit=limit,
            offset=offset,
            request_options=request_options,
        )
        return _response.data


class AsyncDownloadsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawDownloadsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawDownloadsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawDownloadsClient
        """
        return self._raw_client

    async def list(
        self,
        *,
        q: typing.Optional[str] = None,
        mime_type: typing.Optional[str] = None,
        min_size_bytes: typing.Optional[int] = None,
        max_size_bytes: typing.Optional[int] = None,
        created_after: typing.Optional[dt.datetime] = None,
        created_before: typing.Optional[dt.datetime] = None,
        limit: typing.Optional[int] = None,
        offset: typing.Optional[int] = None,
        session_id: typing.Optional[str] = None,
        sort: typing.Optional[DownloadsListRequestSort] = None,
        order: typing.Optional[DownloadsListRequestOrder] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> FileDownloadListResponse:
        """
        Returns one page of the files captured off phones during sessions (AXI-1449), newest first. Each row carries its capture state: a skipped or failed capture is a visible entry with a reason, not an absence. Downloads share the library and its storage quota with uploads, and a ready download can be delivered to a phone by its id like any upload.

        Parameters
        ----------
        q : typing.Optional[str]
            filter by filename, case-insensitive substring match

        mime_type : typing.Optional[str]
            only downloads of exactly this media type

        min_size_bytes : typing.Optional[int]
            only downloads at least this many bytes (0 = no bound)

        max_size_bytes : typing.Optional[int]
            only downloads at most this many bytes (0 = no bound)

        created_after : typing.Optional[dt.datetime]
            only downloads registered at or after this time (RFC 3339)

        created_before : typing.Optional[dt.datetime]
            only downloads registered at or before this time (RFC 3339)

        limit : typing.Optional[int]
            max items per page

        offset : typing.Optional[int]
            pagination offset

        session_id : typing.Optional[str]
            only downloads captured by this session

        sort : typing.Optional[DownloadsListRequestSort]
            field to sort by

        order : typing.Optional[DownloadsListRequestOrder]
            sort direction

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        FileDownloadListResponse
            OK

        Examples
        --------
        import asyncio

        from axilio import AsyncAxilioApi

        client = AsyncAxilioApi(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.downloads.list()


        asyncio.run(main())
        """
        _response = await self._raw_client.list(
            q=q,
            mime_type=mime_type,
            min_size_bytes=min_size_bytes,
            max_size_bytes=max_size_bytes,
            created_after=created_after,
            created_before=created_before,
            limit=limit,
            offset=offset,
            session_id=session_id,
            sort=sort,
            order=order,
            request_options=request_options,
        )
        return _response.data

    async def delete(
        self, download_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> DeleteFileOutputBody:
        """
        Removes a captured file from the org's library and everywhere it was delivered: the stored object and the library entry go immediately, and every phone the file was pushed to is scheduled to remove its copy (removal is confirmed per phone and retried until it lands), the same recall an upload's delete runs. The response reports how many phones that recall reaches. The source phone's own copy from the capture session is outside the recall: it belongs to the session, not the library.

        Parameters
        ----------
        download_id : str
            download identifier to delete

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        DeleteFileOutputBody
            OK

        Examples
        --------
        import asyncio

        from axilio import AsyncAxilioApi

        client = AsyncAxilioApi(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.downloads.delete(
                download_id="download_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.delete(download_id, request_options=request_options)
        return _response.data

    async def phones_session_downloads(
        self,
        session_id: str,
        *,
        q: typing.Optional[str] = None,
        mime_type: typing.Optional[str] = None,
        min_size_bytes: typing.Optional[int] = None,
        max_size_bytes: typing.Optional[int] = None,
        created_after: typing.Optional[dt.datetime] = None,
        created_before: typing.Optional[dt.datetime] = None,
        limit: typing.Optional[int] = None,
        offset: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> FileDownloadListResponse:
        """
        Returns the files this session captured off its phone, newest first — the direct answer to "what did this session download". Rows appear at detection, before the bytes finish moving, so a caller waiting on a file watches its capture state progress rather than an empty list.

        Parameters
        ----------
        session_id : str
            session whose captures to list

        q : typing.Optional[str]
            filter by filename, case-insensitive substring match

        mime_type : typing.Optional[str]
            only downloads of exactly this media type

        min_size_bytes : typing.Optional[int]
            only downloads at least this many bytes (0 = no bound)

        max_size_bytes : typing.Optional[int]
            only downloads at most this many bytes (0 = no bound)

        created_after : typing.Optional[dt.datetime]
            only downloads registered at or after this time (RFC 3339)

        created_before : typing.Optional[dt.datetime]
            only downloads registered at or before this time (RFC 3339)

        limit : typing.Optional[int]
            max items per page

        offset : typing.Optional[int]
            pagination offset

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        FileDownloadListResponse
            OK

        Examples
        --------
        import asyncio

        from axilio import AsyncAxilioApi

        client = AsyncAxilioApi(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.downloads.phones_session_downloads(
                session_id="session_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.phones_session_downloads(
            session_id,
            q=q,
            mime_type=mime_type,
            min_size_bytes=min_size_bytes,
            max_size_bytes=max_size_bytes,
            created_after=created_after,
            created_before=created_before,
            limit=limit,
            offset=offset,
            request_options=request_options,
        )
        return _response.data
