# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing
from json.decoder import JSONDecodeError

from ..core.api_error import ApiError
from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.datetime_utils import serialize_datetime
from ..core.http_response import AsyncHttpResponse, HttpResponse
from ..core.parse_error import ParsingError
from ..core.pydantic_utilities import parse_obj_as
from ..core.request_options import RequestOptions
from ..core.serialization import convert_and_respect_annotation_metadata
from ..types.usage_inference_sort_spec import UsageInferenceSortSpec
from ..types.usage_inferences_response import UsageInferencesResponse
from ..types.usage_usage_metrics_response import UsageUsageMetricsResponse
from .types.usage_get_metrics_request_granularity import UsageGetMetricsRequestGranularity
from pydantic import ValidationError

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class RawUsageClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._client_wrapper = client_wrapper

    def list_inferences(
        self,
        *,
        end_date: dt.datetime,
        start_date: dt.datetime,
        endpoint_filter: typing.Optional[typing.Sequence[str]] = OMIT,
        limit: typing.Optional[int] = OMIT,
        model: typing.Optional[str] = OMIT,
        offset: typing.Optional[int] = OMIT,
        search: typing.Optional[str] = OMIT,
        session_id: typing.Optional[str] = OMIT,
        sort_by: typing.Optional[typing.Sequence[UsageInferenceSortSpec]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[UsageInferencesResponse]:
        """
        Paginated, filterable list of inference calls (/infer + /locate) the caller's user was billed for. Filters: date range, endpoint, free-text search. Ordered by call time DESC.

        Parameters
        ----------
        end_date : dt.datetime

        start_date : dt.datetime

        endpoint_filter : typing.Optional[typing.Sequence[str]]

        limit : typing.Optional[int]

        model : typing.Optional[str]

        offset : typing.Optional[int]

        search : typing.Optional[str]

        session_id : typing.Optional[str]

        sort_by : typing.Optional[typing.Sequence[UsageInferenceSortSpec]]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[UsageInferencesResponse]
            OK
        """
        _response = self._client_wrapper.httpx_client.request(
            "usage/inferences",
            method="POST",
            json={
                "end_date": end_date,
                "endpoint_filter": endpoint_filter,
                "limit": limit,
                "model": model,
                "offset": offset,
                "search": search,
                "session_id": session_id,
                "sort_by": convert_and_respect_annotation_metadata(
                    object_=sort_by,
                    annotation=typing.Optional[typing.Sequence[UsageInferenceSortSpec]],
                    direction="write",
                ),
                "start_date": start_date,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    UsageInferencesResponse,
                    parse_obj_as(
                        type_=UsageInferencesResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def get_metrics(
        self,
        *,
        start_date: dt.datetime,
        end_date: dt.datetime,
        granularity: typing.Optional[UsageGetMetricsRequestGranularity] = None,
        timezone: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[UsageUsageMetricsResponse]:
        """
        Returns infrastructure cost and compute-minute summaries for the caller's user over a date range, plus per-bucket chart data. Granularity is hourly (≤24h window) or daily. Use POST /usage/metrics if you need richer body params; this endpoint takes query params only.

        Parameters
        ----------
        start_date : dt.datetime
            start of reporting window (RFC3339)

        end_date : dt.datetime
            end of reporting window (RFC3339)

        granularity : typing.Optional[UsageGetMetricsRequestGranularity]
            bucket resolution

        timezone : typing.Optional[str]
            IANA timezone for bucketing periods (e.g., America/Los_Angeles)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[UsageUsageMetricsResponse]
            OK
        """
        _response = self._client_wrapper.httpx_client.request(
            "usage/metrics",
            method="GET",
            params={
                "start_date": serialize_datetime(start_date),
                "end_date": serialize_datetime(end_date),
                "granularity": granularity,
                "timezone": timezone,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    UsageUsageMetricsResponse,
                    parse_obj_as(
                        type_=UsageUsageMetricsResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)


class AsyncRawUsageClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._client_wrapper = client_wrapper

    async def list_inferences(
        self,
        *,
        end_date: dt.datetime,
        start_date: dt.datetime,
        endpoint_filter: typing.Optional[typing.Sequence[str]] = OMIT,
        limit: typing.Optional[int] = OMIT,
        model: typing.Optional[str] = OMIT,
        offset: typing.Optional[int] = OMIT,
        search: typing.Optional[str] = OMIT,
        session_id: typing.Optional[str] = OMIT,
        sort_by: typing.Optional[typing.Sequence[UsageInferenceSortSpec]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[UsageInferencesResponse]:
        """
        Paginated, filterable list of inference calls (/infer + /locate) the caller's user was billed for. Filters: date range, endpoint, free-text search. Ordered by call time DESC.

        Parameters
        ----------
        end_date : dt.datetime

        start_date : dt.datetime

        endpoint_filter : typing.Optional[typing.Sequence[str]]

        limit : typing.Optional[int]

        model : typing.Optional[str]

        offset : typing.Optional[int]

        search : typing.Optional[str]

        session_id : typing.Optional[str]

        sort_by : typing.Optional[typing.Sequence[UsageInferenceSortSpec]]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[UsageInferencesResponse]
            OK
        """
        _response = await self._client_wrapper.httpx_client.request(
            "usage/inferences",
            method="POST",
            json={
                "end_date": end_date,
                "endpoint_filter": endpoint_filter,
                "limit": limit,
                "model": model,
                "offset": offset,
                "search": search,
                "session_id": session_id,
                "sort_by": convert_and_respect_annotation_metadata(
                    object_=sort_by,
                    annotation=typing.Optional[typing.Sequence[UsageInferenceSortSpec]],
                    direction="write",
                ),
                "start_date": start_date,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    UsageInferencesResponse,
                    parse_obj_as(
                        type_=UsageInferencesResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def get_metrics(
        self,
        *,
        start_date: dt.datetime,
        end_date: dt.datetime,
        granularity: typing.Optional[UsageGetMetricsRequestGranularity] = None,
        timezone: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[UsageUsageMetricsResponse]:
        """
        Returns infrastructure cost and compute-minute summaries for the caller's user over a date range, plus per-bucket chart data. Granularity is hourly (≤24h window) or daily. Use POST /usage/metrics if you need richer body params; this endpoint takes query params only.

        Parameters
        ----------
        start_date : dt.datetime
            start of reporting window (RFC3339)

        end_date : dt.datetime
            end of reporting window (RFC3339)

        granularity : typing.Optional[UsageGetMetricsRequestGranularity]
            bucket resolution

        timezone : typing.Optional[str]
            IANA timezone for bucketing periods (e.g., America/Los_Angeles)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[UsageUsageMetricsResponse]
            OK
        """
        _response = await self._client_wrapper.httpx_client.request(
            "usage/metrics",
            method="GET",
            params={
                "start_date": serialize_datetime(start_date),
                "end_date": serialize_datetime(end_date),
                "granularity": granularity,
                "timezone": timezone,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    UsageUsageMetricsResponse,
                    parse_obj_as(
                        type_=UsageUsageMetricsResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)
