# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.phone_active_sessions_response import PhoneActiveSessionsResponse
from ..types.phone_allocate_response import PhoneAllocateResponse
from ..types.phone_available_list_response import PhoneAvailableListResponse
from ..types.phone_deallocate_response import PhoneDeallocateResponse
from ..types.phone_live_view_options import PhoneLiveViewOptions
from ..types.phone_private_list_response import PhonePrivateListResponse
from ..types.phone_session_detail_response import PhoneSessionDetailResponse
from ..types.phone_session_list_response import PhoneSessionListResponse
from ..types.phone_session_recording_response import PhoneSessionRecordingResponse
from ..types.phone_session_thumbnail_response import PhoneSessionThumbnailResponse
from ..types.phone_session_ttl_options import PhoneSessionTtlOptions
from ..types.phone_success_response import PhoneSuccessResponse
from ..types.phone_summary import PhoneSummary
from ..types.phone_supported_apps_response import PhoneSupportedAppsResponse
from .raw_client import AsyncRawPhonesClient, RawPhonesClient
from .types.phone_allocate_request_phone_type import PhoneAllocateRequestPhoneType

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class PhonesClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawPhonesClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawPhonesClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawPhonesClient
        """
        return self._raw_client

    def allocate(
        self,
        *,
        phone_type: PhoneAllocateRequestPhoneType,
        live_view: typing.Optional[PhoneLiveViewOptions] = OMIT,
        name: typing.Optional[str] = OMIT,
        phone_id: typing.Optional[str] = OMIT,
        recording: typing.Optional[bool] = OMIT,
        tags: typing.Optional[typing.Dict[str, str]] = OMIT,
        telemetry: typing.Optional[bool] = OMIT,
        ttl: typing.Optional[PhoneSessionTtlOptions] = OMIT,
        workflow_id: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PhoneAllocateResponse:
        """
        Allocates a phone and opens a session. Omit workflow_id for an interactive lease (drive the phone directly); set it to allocate for a workflow. Pass phone_id to pin a specific dedicated phone. If allocation setup fails the claim is rolled back, so you are never billed for a session that never starts.

        Parameters
        ----------
        phone_type : PhoneAllocateRequestPhoneType
            Category of device to allocate.

        live_view : typing.Optional[PhoneLiveViewOptions]
            Hosted live-view options for this session; omit for the defaults (token auth, interactive, enabled).

        name : typing.Optional[str]
            Optional session label (letters, numbers, dots, hyphens, underscores; max 64). Unique among the org's active sessions - allocating with a name already in use returns a conflict.

        phone_id : typing.Optional[str]
            PhoneID pins allocation to a specific device (for dedicated devices).

        recording : typing.Optional[bool]
            Record this session's screen (default true). false suppresses the video recording and rolling thumbnail entirely - no screen content is ever written.

        tags : typing.Optional[typing.Dict[str, str]]
            Optional key->value labels for organizing sessions (max 50 tags; keys up to 40 chars, values up to 128).

        telemetry : typing.Optional[bool]
            Persist this session's telemetry spans (default true). false skips the durable trace store; the live telemetry stream still works while the session runs.

        ttl : typing.Optional[PhoneSessionTtlOptions]
            Idle-timeout override for this session; omit for the defaults (inactive after 5 min, close 10 min later).

        workflow_id : typing.Optional[str]
            Workflow requesting allocation; nil for an interactive lease.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PhoneAllocateResponse
            OK

        Examples
        --------
        from axilio import AxilioApi

        client = AxilioApi(
            api_key="YOUR_API_KEY",
        )
        client.phones.allocate(
            phone_type="android",
        )
        """
        _response = self._raw_client.allocate(
            phone_type=phone_type,
            live_view=live_view,
            name=name,
            phone_id=phone_id,
            recording=recording,
            tags=tags,
            telemetry=telemetry,
            ttl=ttl,
            workflow_id=workflow_id,
            request_options=request_options,
        )
        return _response.data

    def supported_apps(
        self,
        *,
        platform: typing.Optional[str] = None,
        category: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PhoneSupportedAppsResponse:
        """
        Returns the apps the platform supports orchestration for, optionally filtered by platform and category.

        Parameters
        ----------
        platform : typing.Optional[str]
            filter by platform

        category : typing.Optional[str]
            filter by app category

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PhoneSupportedAppsResponse
            OK

        Examples
        --------
        from axilio import AxilioApi

        client = AxilioApi(
            api_key="YOUR_API_KEY",
        )
        client.phones.supported_apps()
        """
        _response = self._raw_client.supported_apps(
            platform=platform, category=category, request_options=request_options
        )
        return _response.data

    def available(
        self, *, device_type: typing.Optional[str] = None, request_options: typing.Optional[RequestOptions] = None
    ) -> PhoneAvailableListResponse:
        """
        Returns ACTIVE unallocated phones the caller's org can claim, optionally filtered by phone type (iphone/android). Counts by type are included alongside the list.

        Parameters
        ----------
        device_type : typing.Optional[str]
            filter by device type (iphone/android)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PhoneAvailableListResponse
            OK

        Examples
        --------
        from axilio import AxilioApi

        client = AxilioApi(
            api_key="YOUR_API_KEY",
        )
        client.phones.available()
        """
        _response = self._raw_client.available(device_type=device_type, request_options=request_options)
        return _response.data

    def deallocate(
        self, *, phone_id: str, request_options: typing.Optional[RequestOptions] = None
    ) -> PhoneDeallocateResponse:
        """
        Deallocates a phone the caller's org currently holds. The session is billed and the phone is torn down asynchronously.

        Parameters
        ----------
        phone_id : str
            device identifier to deallocate

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PhoneDeallocateResponse
            OK

        Examples
        --------
        from axilio import AxilioApi

        client = AxilioApi(
            api_key="YOUR_API_KEY",
        )
        client.phones.deallocate(
            phone_id="phone_id",
        )
        """
        _response = self._raw_client.deallocate(phone_id=phone_id, request_options=request_options)
        return _response.data

    def mine(
        self,
        *,
        include_expired: typing.Optional[bool] = None,
        limit: typing.Optional[int] = None,
        offset: typing.Optional[int] = None,
        search: typing.Optional[str] = None,
        status: typing.Optional[typing.Sequence[str]] = None,
        type: typing.Optional[typing.Sequence[str]] = None,
        rental_expires_after: typing.Optional[str] = None,
        rental_expires_before: typing.Optional[str] = None,
        last_active_after: typing.Optional[str] = None,
        last_active_before: typing.Optional[str] = None,
        sort: typing.Optional[str] = None,
        order: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PhonePrivateListResponse:
        """
        Returns private and rented phones owned by the caller's org. include_expired=true keeps rentals past their rental_expires_at in the result so users can see what they used to own.

        Parameters
        ----------
        include_expired : typing.Optional[bool]
            include rented devices whose rental window has expired

        limit : typing.Optional[int]

        offset : typing.Optional[int]

        search : typing.Optional[str]
            free-text search across nickname, name, model, location

        status : typing.Optional[typing.Sequence[str]]
            filter by phone status (ACTIVE/INACTIVE/MAINTENANCE/SUSPENDED)

        type : typing.Optional[typing.Sequence[str]]
            filter by phone type (IPHONE/ANDROID)

        rental_expires_after : typing.Optional[str]
            only phones whose rental expires at/after this RFC3339 time

        rental_expires_before : typing.Optional[str]
            only phones whose rental expires at/before this RFC3339 time

        last_active_after : typing.Optional[str]
            only phones last seen at/after this RFC3339 time

        last_active_before : typing.Optional[str]
            only phones last seen at/before this RFC3339 time

        sort : typing.Optional[str]
            sort column (created|rental_expires|last_active|status|type|location)

        order : typing.Optional[str]
            sort direction (asc|desc)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PhonePrivateListResponse
            OK

        Examples
        --------
        from axilio import AxilioApi

        client = AxilioApi(
            api_key="YOUR_API_KEY",
        )
        client.phones.mine()
        """
        _response = self._raw_client.mine(
            include_expired=include_expired,
            limit=limit,
            offset=offset,
            search=search,
            status=status,
            type=type,
            rental_expires_after=rental_expires_after,
            rental_expires_before=rental_expires_before,
            last_active_after=last_active_after,
            last_active_before=last_active_before,
            sort=sort,
            order=order,
            request_options=request_options,
        )
        return _response.data

    def list_sessions(
        self,
        *,
        limit: typing.Optional[int] = None,
        offset: typing.Optional[int] = None,
        search: typing.Optional[str] = None,
        workflow_id: typing.Optional[str] = None,
        status: typing.Optional[typing.Sequence[str]] = None,
        source: typing.Optional[typing.Sequence[str]] = None,
        dedicated: typing.Optional[typing.Sequence[str]] = None,
        started_after: typing.Optional[str] = None,
        started_before: typing.Optional[str] = None,
        ended_after: typing.Optional[str] = None,
        ended_before: typing.Optional[str] = None,
        sort: typing.Optional[str] = None,
        order: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PhoneSessionListResponse:
        """
        Returns one page of the org's phone sessions for the Session Inspector table: active/unbilled sessions pinned on top, terminal history paginated beneath. Covers workflow runs and workflow-less interactive leases; each row links to a session. Filters: search, workflow_id, status.

        Parameters
        ----------
        limit : typing.Optional[int]
            max rows to return (default 50, max 100)

        offset : typing.Optional[int]
            rows to skip for pagination

        search : typing.Optional[str]
            case-insensitive match on phone/session/workflow

        workflow_id : typing.Optional[str]
            only sessions for this workflow

        status : typing.Optional[typing.Sequence[str]]
            filter by session status (ACTIVE/COMPLETED/CANCELLED/EXPIRED); repeatable

        source : typing.Optional[typing.Sequence[str]]
            filter by source: workflow and/or interactive; repeatable

        dedicated : typing.Optional[typing.Sequence[str]]
            filter by type: shared and/or dedicated; repeatable

        started_after : typing.Optional[str]
            only sessions started at/after this RFC3339 time

        started_before : typing.Optional[str]
            only sessions started at/before this RFC3339 time

        ended_after : typing.Optional[str]
            only sessions de-allocated at/after this RFC3339 time

        ended_before : typing.Optional[str]
            only sessions de-allocated at/before this RFC3339 time

        sort : typing.Optional[str]
            sort column: started|ended|status|duration (default started)

        order : typing.Optional[str]
            sort direction: asc|desc (default desc)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PhoneSessionListResponse
            OK

        Examples
        --------
        from axilio import AxilioApi

        client = AxilioApi(
            api_key="YOUR_API_KEY",
        )
        client.phones.list_sessions()
        """
        _response = self._raw_client.list_sessions(
            limit=limit,
            offset=offset,
            search=search,
            workflow_id=workflow_id,
            status=status,
            source=source,
            dedicated=dedicated,
            started_after=started_after,
            started_before=started_before,
            ended_after=ended_after,
            ended_before=ended_before,
            sort=sort,
            order=order,
            request_options=request_options,
        )
        return _response.data

    def active_sessions(
        self,
        *,
        limit: typing.Optional[int] = None,
        offset: typing.Optional[int] = None,
        search: typing.Optional[str] = None,
        dedicated: typing.Optional[str] = None,
        source: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PhoneActiveSessionsResponse:
        """
        Returns one page of the organization's currently-active phone sessions joined with phone + workflow display fields: in-flight runs, workflow-less interactive leases, and dedicated phones in use. Paginated via limit (default 25, max 100) + offset; the response total is the full active count.

        Parameters
        ----------
        limit : typing.Optional[int]
            max rows to return (default 25, max 100)

        offset : typing.Optional[int]
            rows to skip for pagination

        search : typing.Optional[str]
            case-insensitive match on phone name/nickname/id, session id, or workflow name

        dedicated : typing.Optional[str]
            filter by ownership: 'dedicated' or 'shared'

        source : typing.Optional[str]
            filter by source: 'workflow' or 'interactive'

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PhoneActiveSessionsResponse
            OK

        Examples
        --------
        from axilio import AxilioApi

        client = AxilioApi(
            api_key="YOUR_API_KEY",
        )
        client.phones.active_sessions()
        """
        _response = self._raw_client.active_sessions(
            limit=limit,
            offset=offset,
            search=search,
            dedicated=dedicated,
            source=source,
            request_options=request_options,
        )
        return _response.data

    def get_session(
        self, session_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> PhoneSessionDetailResponse:
        """
        Returns one session for the Session Inspector: session lifecycle + phone display fields + workflow name (when tied to one) + an inlined presigned recording URL. Works for active and terminal sessions, and for workflow runs and workflow-less interactive leases. Org-scoped: another org's session reads as not found.

        Parameters
        ----------
        session_id : str
            Phone session identifier

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PhoneSessionDetailResponse
            OK

        Examples
        --------
        from axilio import AxilioApi

        client = AxilioApi(
            api_key="YOUR_API_KEY",
        )
        client.phones.get_session(
            session_id="session_id",
        )
        """
        _response = self._raw_client.get_session(session_id, request_options=request_options)
        return _response.data

    def session_recording(
        self, session_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> PhoneSessionRecordingResponse:
        """
        Returns a short-lived URL for the session's screen recording, keyed on session_id — so it works for workflow runs and workflow-less interactive leases alike. Status is "pending" (no URL) when the recording hasn't finished uploading yet. Org-scoped: another org's session reads as not found.

        Parameters
        ----------
        session_id : str
            Phone session identifier

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PhoneSessionRecordingResponse
            OK

        Examples
        --------
        from axilio import AxilioApi

        client = AxilioApi(
            api_key="YOUR_API_KEY",
        )
        client.phones.session_recording(
            session_id="session_id",
        )
        """
        _response = self._raw_client.session_recording(session_id, request_options=request_options)
        return _response.data

    def session_thumbnail(
        self, session_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> PhoneSessionThumbnailResponse:
        """
        Returns a short-lived URL for the session's current screen thumbnail — a rolling JPEG refreshed every few seconds while the session is active. Poll this endpoint and swap the image; every call mints a fresh URL. Status is "pending" (no URL) before the first frame lands or after the session ends. Org-scoped: another org's session reads as not found.

        Parameters
        ----------
        session_id : str
            Phone session identifier

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PhoneSessionThumbnailResponse
            OK

        Examples
        --------
        from axilio import AxilioApi

        client = AxilioApi(
            api_key="YOUR_API_KEY",
        )
        client.phones.session_thumbnail(
            session_id="session_id",
        )
        """
        _response = self._raw_client.session_thumbnail(session_id, request_options=request_options)
        return _response.data

    def get(self, phone_id: str, *, request_options: typing.Optional[RequestOptions] = None) -> PhoneSummary:
        """
        Returns a single phone by its identifier.

        Parameters
        ----------
        phone_id : str
            device identifier

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PhoneSummary
            OK

        Examples
        --------
        from axilio import AxilioApi

        client = AxilioApi(
            api_key="YOUR_API_KEY",
        )
        client.phones.get(
            phone_id="phone_id",
        )
        """
        _response = self._raw_client.get(phone_id, request_options=request_options)
        return _response.data

    def nickname(
        self, phone_id: str, *, nickname: str, request_options: typing.Optional[RequestOptions] = None
    ) -> PhoneSummary:
        """
        Sets the human-readable display name on a private phone the caller's org owns. Returns the updated phone summary.

        Parameters
        ----------
        phone_id : str
            device identifier

        nickname : str
            New display name for the device.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PhoneSummary
            OK

        Examples
        --------
        from axilio import AxilioApi

        client = AxilioApi(
            api_key="YOUR_API_KEY",
        )
        client.phones.nickname(
            phone_id="phone_id",
            nickname="nickname",
        )
        """
        _response = self._raw_client.nickname(phone_id, nickname=nickname, request_options=request_options)
        return _response.data

    def wipe(self, phone_id: str, *, request_options: typing.Optional[RequestOptions] = None) -> PhoneSuccessResponse:
        """
        Requests an on-demand factory reset of a private phone the caller's org owns. Requires the phone to be ACTIVE and not currently allocated. Sets the phone to MAINTENANCE while the wipe is carried out.

        Parameters
        ----------
        phone_id : str
            device identifier

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PhoneSuccessResponse
            OK

        Examples
        --------
        from axilio import AxilioApi

        client = AxilioApi(
            api_key="YOUR_API_KEY",
        )
        client.phones.wipe(
            phone_id="phone_id",
        )
        """
        _response = self._raw_client.wipe(phone_id, request_options=request_options)
        return _response.data


class AsyncPhonesClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawPhonesClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawPhonesClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawPhonesClient
        """
        return self._raw_client

    async def allocate(
        self,
        *,
        phone_type: PhoneAllocateRequestPhoneType,
        live_view: typing.Optional[PhoneLiveViewOptions] = OMIT,
        name: typing.Optional[str] = OMIT,
        phone_id: typing.Optional[str] = OMIT,
        recording: typing.Optional[bool] = OMIT,
        tags: typing.Optional[typing.Dict[str, str]] = OMIT,
        telemetry: typing.Optional[bool] = OMIT,
        ttl: typing.Optional[PhoneSessionTtlOptions] = OMIT,
        workflow_id: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PhoneAllocateResponse:
        """
        Allocates a phone and opens a session. Omit workflow_id for an interactive lease (drive the phone directly); set it to allocate for a workflow. Pass phone_id to pin a specific dedicated phone. If allocation setup fails the claim is rolled back, so you are never billed for a session that never starts.

        Parameters
        ----------
        phone_type : PhoneAllocateRequestPhoneType
            Category of device to allocate.

        live_view : typing.Optional[PhoneLiveViewOptions]
            Hosted live-view options for this session; omit for the defaults (token auth, interactive, enabled).

        name : typing.Optional[str]
            Optional session label (letters, numbers, dots, hyphens, underscores; max 64). Unique among the org's active sessions - allocating with a name already in use returns a conflict.

        phone_id : typing.Optional[str]
            PhoneID pins allocation to a specific device (for dedicated devices).

        recording : typing.Optional[bool]
            Record this session's screen (default true). false suppresses the video recording and rolling thumbnail entirely - no screen content is ever written.

        tags : typing.Optional[typing.Dict[str, str]]
            Optional key->value labels for organizing sessions (max 50 tags; keys up to 40 chars, values up to 128).

        telemetry : typing.Optional[bool]
            Persist this session's telemetry spans (default true). false skips the durable trace store; the live telemetry stream still works while the session runs.

        ttl : typing.Optional[PhoneSessionTtlOptions]
            Idle-timeout override for this session; omit for the defaults (inactive after 5 min, close 10 min later).

        workflow_id : typing.Optional[str]
            Workflow requesting allocation; nil for an interactive lease.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PhoneAllocateResponse
            OK

        Examples
        --------
        import asyncio

        from axilio import AsyncAxilioApi

        client = AsyncAxilioApi(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.phones.allocate(
                phone_type="android",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.allocate(
            phone_type=phone_type,
            live_view=live_view,
            name=name,
            phone_id=phone_id,
            recording=recording,
            tags=tags,
            telemetry=telemetry,
            ttl=ttl,
            workflow_id=workflow_id,
            request_options=request_options,
        )
        return _response.data

    async def supported_apps(
        self,
        *,
        platform: typing.Optional[str] = None,
        category: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PhoneSupportedAppsResponse:
        """
        Returns the apps the platform supports orchestration for, optionally filtered by platform and category.

        Parameters
        ----------
        platform : typing.Optional[str]
            filter by platform

        category : typing.Optional[str]
            filter by app category

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PhoneSupportedAppsResponse
            OK

        Examples
        --------
        import asyncio

        from axilio import AsyncAxilioApi

        client = AsyncAxilioApi(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.phones.supported_apps()


        asyncio.run(main())
        """
        _response = await self._raw_client.supported_apps(
            platform=platform, category=category, request_options=request_options
        )
        return _response.data

    async def available(
        self, *, device_type: typing.Optional[str] = None, request_options: typing.Optional[RequestOptions] = None
    ) -> PhoneAvailableListResponse:
        """
        Returns ACTIVE unallocated phones the caller's org can claim, optionally filtered by phone type (iphone/android). Counts by type are included alongside the list.

        Parameters
        ----------
        device_type : typing.Optional[str]
            filter by device type (iphone/android)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PhoneAvailableListResponse
            OK

        Examples
        --------
        import asyncio

        from axilio import AsyncAxilioApi

        client = AsyncAxilioApi(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.phones.available()


        asyncio.run(main())
        """
        _response = await self._raw_client.available(device_type=device_type, request_options=request_options)
        return _response.data

    async def deallocate(
        self, *, phone_id: str, request_options: typing.Optional[RequestOptions] = None
    ) -> PhoneDeallocateResponse:
        """
        Deallocates a phone the caller's org currently holds. The session is billed and the phone is torn down asynchronously.

        Parameters
        ----------
        phone_id : str
            device identifier to deallocate

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PhoneDeallocateResponse
            OK

        Examples
        --------
        import asyncio

        from axilio import AsyncAxilioApi

        client = AsyncAxilioApi(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.phones.deallocate(
                phone_id="phone_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.deallocate(phone_id=phone_id, request_options=request_options)
        return _response.data

    async def mine(
        self,
        *,
        include_expired: typing.Optional[bool] = None,
        limit: typing.Optional[int] = None,
        offset: typing.Optional[int] = None,
        search: typing.Optional[str] = None,
        status: typing.Optional[typing.Sequence[str]] = None,
        type: typing.Optional[typing.Sequence[str]] = None,
        rental_expires_after: typing.Optional[str] = None,
        rental_expires_before: typing.Optional[str] = None,
        last_active_after: typing.Optional[str] = None,
        last_active_before: typing.Optional[str] = None,
        sort: typing.Optional[str] = None,
        order: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PhonePrivateListResponse:
        """
        Returns private and rented phones owned by the caller's org. include_expired=true keeps rentals past their rental_expires_at in the result so users can see what they used to own.

        Parameters
        ----------
        include_expired : typing.Optional[bool]
            include rented devices whose rental window has expired

        limit : typing.Optional[int]

        offset : typing.Optional[int]

        search : typing.Optional[str]
            free-text search across nickname, name, model, location

        status : typing.Optional[typing.Sequence[str]]
            filter by phone status (ACTIVE/INACTIVE/MAINTENANCE/SUSPENDED)

        type : typing.Optional[typing.Sequence[str]]
            filter by phone type (IPHONE/ANDROID)

        rental_expires_after : typing.Optional[str]
            only phones whose rental expires at/after this RFC3339 time

        rental_expires_before : typing.Optional[str]
            only phones whose rental expires at/before this RFC3339 time

        last_active_after : typing.Optional[str]
            only phones last seen at/after this RFC3339 time

        last_active_before : typing.Optional[str]
            only phones last seen at/before this RFC3339 time

        sort : typing.Optional[str]
            sort column (created|rental_expires|last_active|status|type|location)

        order : typing.Optional[str]
            sort direction (asc|desc)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PhonePrivateListResponse
            OK

        Examples
        --------
        import asyncio

        from axilio import AsyncAxilioApi

        client = AsyncAxilioApi(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.phones.mine()


        asyncio.run(main())
        """
        _response = await self._raw_client.mine(
            include_expired=include_expired,
            limit=limit,
            offset=offset,
            search=search,
            status=status,
            type=type,
            rental_expires_after=rental_expires_after,
            rental_expires_before=rental_expires_before,
            last_active_after=last_active_after,
            last_active_before=last_active_before,
            sort=sort,
            order=order,
            request_options=request_options,
        )
        return _response.data

    async def list_sessions(
        self,
        *,
        limit: typing.Optional[int] = None,
        offset: typing.Optional[int] = None,
        search: typing.Optional[str] = None,
        workflow_id: typing.Optional[str] = None,
        status: typing.Optional[typing.Sequence[str]] = None,
        source: typing.Optional[typing.Sequence[str]] = None,
        dedicated: typing.Optional[typing.Sequence[str]] = None,
        started_after: typing.Optional[str] = None,
        started_before: typing.Optional[str] = None,
        ended_after: typing.Optional[str] = None,
        ended_before: typing.Optional[str] = None,
        sort: typing.Optional[str] = None,
        order: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PhoneSessionListResponse:
        """
        Returns one page of the org's phone sessions for the Session Inspector table: active/unbilled sessions pinned on top, terminal history paginated beneath. Covers workflow runs and workflow-less interactive leases; each row links to a session. Filters: search, workflow_id, status.

        Parameters
        ----------
        limit : typing.Optional[int]
            max rows to return (default 50, max 100)

        offset : typing.Optional[int]
            rows to skip for pagination

        search : typing.Optional[str]
            case-insensitive match on phone/session/workflow

        workflow_id : typing.Optional[str]
            only sessions for this workflow

        status : typing.Optional[typing.Sequence[str]]
            filter by session status (ACTIVE/COMPLETED/CANCELLED/EXPIRED); repeatable

        source : typing.Optional[typing.Sequence[str]]
            filter by source: workflow and/or interactive; repeatable

        dedicated : typing.Optional[typing.Sequence[str]]
            filter by type: shared and/or dedicated; repeatable

        started_after : typing.Optional[str]
            only sessions started at/after this RFC3339 time

        started_before : typing.Optional[str]
            only sessions started at/before this RFC3339 time

        ended_after : typing.Optional[str]
            only sessions de-allocated at/after this RFC3339 time

        ended_before : typing.Optional[str]
            only sessions de-allocated at/before this RFC3339 time

        sort : typing.Optional[str]
            sort column: started|ended|status|duration (default started)

        order : typing.Optional[str]
            sort direction: asc|desc (default desc)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PhoneSessionListResponse
            OK

        Examples
        --------
        import asyncio

        from axilio import AsyncAxilioApi

        client = AsyncAxilioApi(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.phones.list_sessions()


        asyncio.run(main())
        """
        _response = await self._raw_client.list_sessions(
            limit=limit,
            offset=offset,
            search=search,
            workflow_id=workflow_id,
            status=status,
            source=source,
            dedicated=dedicated,
            started_after=started_after,
            started_before=started_before,
            ended_after=ended_after,
            ended_before=ended_before,
            sort=sort,
            order=order,
            request_options=request_options,
        )
        return _response.data

    async def active_sessions(
        self,
        *,
        limit: typing.Optional[int] = None,
        offset: typing.Optional[int] = None,
        search: typing.Optional[str] = None,
        dedicated: typing.Optional[str] = None,
        source: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PhoneActiveSessionsResponse:
        """
        Returns one page of the organization's currently-active phone sessions joined with phone + workflow display fields: in-flight runs, workflow-less interactive leases, and dedicated phones in use. Paginated via limit (default 25, max 100) + offset; the response total is the full active count.

        Parameters
        ----------
        limit : typing.Optional[int]
            max rows to return (default 25, max 100)

        offset : typing.Optional[int]
            rows to skip for pagination

        search : typing.Optional[str]
            case-insensitive match on phone name/nickname/id, session id, or workflow name

        dedicated : typing.Optional[str]
            filter by ownership: 'dedicated' or 'shared'

        source : typing.Optional[str]
            filter by source: 'workflow' or 'interactive'

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PhoneActiveSessionsResponse
            OK

        Examples
        --------
        import asyncio

        from axilio import AsyncAxilioApi

        client = AsyncAxilioApi(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.phones.active_sessions()


        asyncio.run(main())
        """
        _response = await self._raw_client.active_sessions(
            limit=limit,
            offset=offset,
            search=search,
            dedicated=dedicated,
            source=source,
            request_options=request_options,
        )
        return _response.data

    async def get_session(
        self, session_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> PhoneSessionDetailResponse:
        """
        Returns one session for the Session Inspector: session lifecycle + phone display fields + workflow name (when tied to one) + an inlined presigned recording URL. Works for active and terminal sessions, and for workflow runs and workflow-less interactive leases. Org-scoped: another org's session reads as not found.

        Parameters
        ----------
        session_id : str
            Phone session identifier

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PhoneSessionDetailResponse
            OK

        Examples
        --------
        import asyncio

        from axilio import AsyncAxilioApi

        client = AsyncAxilioApi(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.phones.get_session(
                session_id="session_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_session(session_id, request_options=request_options)
        return _response.data

    async def session_recording(
        self, session_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> PhoneSessionRecordingResponse:
        """
        Returns a short-lived URL for the session's screen recording, keyed on session_id — so it works for workflow runs and workflow-less interactive leases alike. Status is "pending" (no URL) when the recording hasn't finished uploading yet. Org-scoped: another org's session reads as not found.

        Parameters
        ----------
        session_id : str
            Phone session identifier

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PhoneSessionRecordingResponse
            OK

        Examples
        --------
        import asyncio

        from axilio import AsyncAxilioApi

        client = AsyncAxilioApi(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.phones.session_recording(
                session_id="session_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.session_recording(session_id, request_options=request_options)
        return _response.data

    async def session_thumbnail(
        self, session_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> PhoneSessionThumbnailResponse:
        """
        Returns a short-lived URL for the session's current screen thumbnail — a rolling JPEG refreshed every few seconds while the session is active. Poll this endpoint and swap the image; every call mints a fresh URL. Status is "pending" (no URL) before the first frame lands or after the session ends. Org-scoped: another org's session reads as not found.

        Parameters
        ----------
        session_id : str
            Phone session identifier

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PhoneSessionThumbnailResponse
            OK

        Examples
        --------
        import asyncio

        from axilio import AsyncAxilioApi

        client = AsyncAxilioApi(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.phones.session_thumbnail(
                session_id="session_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.session_thumbnail(session_id, request_options=request_options)
        return _response.data

    async def get(self, phone_id: str, *, request_options: typing.Optional[RequestOptions] = None) -> PhoneSummary:
        """
        Returns a single phone by its identifier.

        Parameters
        ----------
        phone_id : str
            device identifier

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PhoneSummary
            OK

        Examples
        --------
        import asyncio

        from axilio import AsyncAxilioApi

        client = AsyncAxilioApi(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.phones.get(
                phone_id="phone_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get(phone_id, request_options=request_options)
        return _response.data

    async def nickname(
        self, phone_id: str, *, nickname: str, request_options: typing.Optional[RequestOptions] = None
    ) -> PhoneSummary:
        """
        Sets the human-readable display name on a private phone the caller's org owns. Returns the updated phone summary.

        Parameters
        ----------
        phone_id : str
            device identifier

        nickname : str
            New display name for the device.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PhoneSummary
            OK

        Examples
        --------
        import asyncio

        from axilio import AsyncAxilioApi

        client = AsyncAxilioApi(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.phones.nickname(
                phone_id="phone_id",
                nickname="nickname",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.nickname(phone_id, nickname=nickname, request_options=request_options)
        return _response.data

    async def wipe(
        self, phone_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> PhoneSuccessResponse:
        """
        Requests an on-demand factory reset of a private phone the caller's org owns. Requires the phone to be ACTIVE and not currently allocated. Sets the phone to MAINTENANCE while the wipe is carried out.

        Parameters
        ----------
        phone_id : str
            device identifier

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PhoneSuccessResponse
            OK

        Examples
        --------
        import asyncio

        from axilio import AsyncAxilioApi

        client = AsyncAxilioApi(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.phones.wipe(
                phone_id="phone_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.wipe(phone_id, request_options=request_options)
        return _response.data
