# This file was auto-generated by Fern from our API Definition.

import typing
from json.decoder import JSONDecodeError

from ..core.api_error import ApiError
from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.http_response import AsyncHttpResponse, HttpResponse
from ..core.parse_error import ParsingError
from ..core.pydantic_utilities import parse_obj_as
from ..core.request_options import RequestOptions
from ..core.serialization import convert_and_respect_annotation_metadata
from ..errors.unprocessable_entity_error import UnprocessableEntityError
from ..types.http_validation_error import HttpValidationError
from ..types.inference_response import InferenceResponse
from ..types.inference_type import InferenceType
from ..types.locate_response import LocateResponse
from ..types.supported_models_response import SupportedModelsResponse
from ..types.text_element_input import TextElementInput
from pydantic import ValidationError

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class RawVisionClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._client_wrapper = client_wrapper

    def detect(
        self,
        *,
        image: str,
        confidence_threshold: typing.Optional[float] = OMIT,
        inference_type: typing.Optional[InferenceType] = OMIT,
        nms_iou_threshold: typing.Optional[float] = OMIT,
        ocr_engine: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[InferenceResponse]:
        """
        Parameters
        ----------
        image : str
            Base64 encoded image data

        confidence_threshold : typing.Optional[float]
            Minimum confidence threshold for detections and OCR results

        inference_type : typing.Optional[InferenceType]
            Type of inference to perform

        nms_iou_threshold : typing.Optional[float]
            IoU threshold for Non-Maximum Suppression (NMS)

        ocr_engine : typing.Optional[str]
            OCR engine to use: 'free' or 'premium'

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[InferenceResponse]
            Successful Response
        """
        _response = self._client_wrapper.httpx_client.request(
            "api/v1/vision/detect",
            method="POST",
            json={
                "confidence_threshold": confidence_threshold,
                "image": image,
                "inference_type": inference_type,
                "nms_iou_threshold": nms_iou_threshold,
                "ocr_engine": ocr_engine,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    InferenceResponse,
                    parse_obj_as(
                        type_=InferenceResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        HttpValidationError,
                        parse_obj_as(
                            type_=HttpValidationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def locate(
        self,
        *,
        image: str,
        query: str,
        model: typing.Optional[str] = OMIT,
        texts: typing.Optional[typing.Sequence[TextElementInput]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[LocateResponse]:
        """
        Parameters
        ----------
        image : str
            Base64 encoded image (PNG or JPEG)

        query : str
            Natural-language target description

        model : typing.Optional[str]
            VLM model to use; must be one of the models from GET /inference/models. Omit to use the server's configured default. The system prompt is fixed to the element-locator task.

        texts : typing.Optional[typing.Sequence[TextElementInput]]
            Pre-computed OCR text elements. Empty list means Argus skips OCR grounding and asks the VLM to locate from the image alone.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[LocateResponse]
            Successful Response
        """
        _response = self._client_wrapper.httpx_client.request(
            "api/v1/vision/locate",
            method="POST",
            json={
                "image": image,
                "model": model,
                "query": query,
                "texts": convert_and_respect_annotation_metadata(
                    object_=texts, annotation=typing.Sequence[TextElementInput], direction="write"
                ),
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    LocateResponse,
                    parse_obj_as(
                        type_=LocateResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        HttpValidationError,
                        parse_obj_as(
                            type_=HttpValidationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def list_models(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[SupportedModelsResponse]:
        """
        List every model Argus supports, with pricing.

        Two families: the curated VLMs served by /vision/locate (per-token
        pricing; pass their id as `model`) and the Axilio model line behind
        /vision/detect (per-page pricing; selected via `ocr_engine` /
        `inference_type` — lite is the free engine, pro is premium).

        Public: no API key required (it's a catalog of model names and public
        prices, nothing sensitive), so a client can discover supported models
        before it holds credentials. The SDK fetches this once, caches it, and
        validates find(model=...) locally so a typo fails fast with a clean
        error instead of a 400 from /locate.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[SupportedModelsResponse]
            Successful Response
        """
        _response = self._client_wrapper.httpx_client.request(
            "api/v1/vision/models",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    SupportedModelsResponse,
                    parse_obj_as(
                        type_=SupportedModelsResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)


class AsyncRawVisionClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._client_wrapper = client_wrapper

    async def detect(
        self,
        *,
        image: str,
        confidence_threshold: typing.Optional[float] = OMIT,
        inference_type: typing.Optional[InferenceType] = OMIT,
        nms_iou_threshold: typing.Optional[float] = OMIT,
        ocr_engine: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[InferenceResponse]:
        """
        Parameters
        ----------
        image : str
            Base64 encoded image data

        confidence_threshold : typing.Optional[float]
            Minimum confidence threshold for detections and OCR results

        inference_type : typing.Optional[InferenceType]
            Type of inference to perform

        nms_iou_threshold : typing.Optional[float]
            IoU threshold for Non-Maximum Suppression (NMS)

        ocr_engine : typing.Optional[str]
            OCR engine to use: 'free' or 'premium'

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[InferenceResponse]
            Successful Response
        """
        _response = await self._client_wrapper.httpx_client.request(
            "api/v1/vision/detect",
            method="POST",
            json={
                "confidence_threshold": confidence_threshold,
                "image": image,
                "inference_type": inference_type,
                "nms_iou_threshold": nms_iou_threshold,
                "ocr_engine": ocr_engine,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    InferenceResponse,
                    parse_obj_as(
                        type_=InferenceResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        HttpValidationError,
                        parse_obj_as(
                            type_=HttpValidationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def locate(
        self,
        *,
        image: str,
        query: str,
        model: typing.Optional[str] = OMIT,
        texts: typing.Optional[typing.Sequence[TextElementInput]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[LocateResponse]:
        """
        Parameters
        ----------
        image : str
            Base64 encoded image (PNG or JPEG)

        query : str
            Natural-language target description

        model : typing.Optional[str]
            VLM model to use; must be one of the models from GET /inference/models. Omit to use the server's configured default. The system prompt is fixed to the element-locator task.

        texts : typing.Optional[typing.Sequence[TextElementInput]]
            Pre-computed OCR text elements. Empty list means Argus skips OCR grounding and asks the VLM to locate from the image alone.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[LocateResponse]
            Successful Response
        """
        _response = await self._client_wrapper.httpx_client.request(
            "api/v1/vision/locate",
            method="POST",
            json={
                "image": image,
                "model": model,
                "query": query,
                "texts": convert_and_respect_annotation_metadata(
                    object_=texts, annotation=typing.Sequence[TextElementInput], direction="write"
                ),
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    LocateResponse,
                    parse_obj_as(
                        type_=LocateResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        HttpValidationError,
                        parse_obj_as(
                            type_=HttpValidationError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def list_models(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[SupportedModelsResponse]:
        """
        List every model Argus supports, with pricing.

        Two families: the curated VLMs served by /vision/locate (per-token
        pricing; pass their id as `model`) and the Axilio model line behind
        /vision/detect (per-page pricing; selected via `ocr_engine` /
        `inference_type` — lite is the free engine, pro is premium).

        Public: no API key required (it's a catalog of model names and public
        prices, nothing sensitive), so a client can discover supported models
        before it holds credentials. The SDK fetches this once, caches it, and
        validates find(model=...) locally so a typo fails fast with a clean
        error instead of a 400 from /locate.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[SupportedModelsResponse]
            Successful Response
        """
        _response = await self._client_wrapper.httpx_client.request(
            "api/v1/vision/models",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    SupportedModelsResponse,
                    parse_obj_as(
                        type_=SupportedModelsResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)
