"""DCP wire constants — re-exported from the generated wire layer.

The Device Control Protocol is literal CDP: the driver's helper methods emit
these "Domain.method" names and both transports send them verbatim —
RemoteTransport as WebSocket messages, SandboxTransport as newline-delimited
JSON on the in-VM daemon's Unix socket. Same frames either way:
``{"id", "method", "params"}`` out, ``{"id", "result"|"error"}`` back.

The method names and error kinds below used to be hand-maintained to mirror the
Go server. They are now generated from the vendored DCP contract into
:mod:`._wire` (see ``scripts/generate_dcp_wire.py``); this module re-exports them
so call sites are unchanged while the source of truth is the contract.
"""

from __future__ import annotations

from ._wire import (
    KIND_ACTION_TIMEOUT,
    KIND_CANCELED,
    KIND_DEVICE_OFFLINE,
    KIND_INTERNAL,
    KIND_INVALID_ARGS,
    KIND_NO_ALLOCATION,
    KIND_NOT_CONNECTED,
    KIND_STALE_NODE,
    KIND_STRATEGY_UNAVAILABLE,
    KIND_TIMEOUT,
    KIND_TREE_UNAVAILABLE,
    KIND_UNAUTHORIZED,
    KIND_UNKNOWN_OP,
    METHOD_ACCESSIBILITY_DISABLE,
    METHOD_ACCESSIBILITY_ENABLE,
    METHOD_ACCESSIBILITY_GET_CHILD_AXNODES,
    METHOD_ACCESSIBILITY_GET_FULL_AXTREE,
    METHOD_ACCESSIBILITY_GET_PARTIAL_AXTREE,
    METHOD_ACCESSIBILITY_GET_STATE,
    METHOD_ACCESSIBILITY_QUERY_AXTREE,
    METHOD_DEVICE_INFO,
    METHOD_KEYBOARD_KEY_PRESS,
    METHOD_KEYBOARD_TYPE_TEXT,
    METHOD_LOCATOR_BOUNDING_BOX,
    METHOD_LOCATOR_COUNT,
    METHOD_LOCATOR_FILL,
    METHOD_LOCATOR_PRESS,
    METHOD_LOCATOR_TAP,
    METHOD_LOCATOR_TEXT,
    METHOD_LOCATOR_WAIT_FOR,
    METHOD_PROTOCOL_HANDSHAKE,
    METHOD_SCREEN_OBSERVE,
    METHOD_SCREEN_SCREENSHOT,
    METHOD_TOUCH_LONG_PRESS,
    METHOD_TOUCH_SWIPE,
    METHOD_TOUCH_TAP,
)

__all__ = [
    "KIND_ACTION_TIMEOUT",
    "KIND_CANCELED",
    "KIND_DEVICE_OFFLINE",
    "KIND_INTERNAL",
    "KIND_INVALID_ARGS",
    "KIND_NO_ALLOCATION",
    "KIND_NOT_CONNECTED",
    "KIND_STALE_NODE",
    "KIND_STRATEGY_UNAVAILABLE",
    "KIND_TIMEOUT",
    "KIND_TREE_UNAVAILABLE",
    "KIND_UNAUTHORIZED",
    "KIND_UNKNOWN_OP",
    "METHOD_ACCESSIBILITY_DISABLE",
    "METHOD_ACCESSIBILITY_ENABLE",
    "METHOD_ACCESSIBILITY_GET_CHILD_AXNODES",
    "METHOD_ACCESSIBILITY_GET_FULL_AXTREE",
    "METHOD_ACCESSIBILITY_GET_PARTIAL_AXTREE",
    "METHOD_ACCESSIBILITY_GET_STATE",
    "METHOD_ACCESSIBILITY_QUERY_AXTREE",
    "METHOD_DEVICE_INFO",
    "METHOD_KEYBOARD_KEY_PRESS",
    "METHOD_KEYBOARD_TYPE_TEXT",
    "METHOD_LOCATOR_BOUNDING_BOX",
    "METHOD_LOCATOR_COUNT",
    "METHOD_LOCATOR_FILL",
    "METHOD_LOCATOR_PRESS",
    "METHOD_LOCATOR_TAP",
    "METHOD_LOCATOR_TEXT",
    "METHOD_LOCATOR_WAIT_FOR",
    "METHOD_PROTOCOL_HANDSHAKE",
    "METHOD_SCREEN_OBSERVE",
    "METHOD_SCREEN_SCREENSHOT",
    "METHOD_TOUCH_LONG_PRESS",
    "METHOD_TOUCH_SWIPE",
    "METHOD_TOUCH_TAP",
]
