# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.complete_file_output_body import CompleteFileOutputBody
from ..types.delete_file_output_body import DeleteFileOutputBody
from ..types.file_list_response import FileListResponse
from ..types.file_upload_response import FileUploadResponse
from ..types.rename_file_output_body import RenameFileOutputBody
from .raw_client import AsyncRawFilesClient, RawFilesClient
from .types.files_list_request_order import FilesListRequestOrder
from .types.files_list_request_sort import FilesListRequestSort
from .types.files_list_request_source import FilesListRequestSource
from .types.files_list_request_surface import FilesListRequestSurface

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class FilesClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawFilesClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawFilesClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawFilesClient
        """
        return self._raw_client

    def list(
        self,
        *,
        limit: typing.Optional[int] = None,
        offset: typing.Optional[int] = None,
        q: typing.Optional[str] = None,
        source: typing.Optional[FilesListRequestSource] = None,
        surface: typing.Optional[FilesListRequestSurface] = None,
        session_id: typing.Optional[str] = None,
        mime_type: typing.Optional[str] = None,
        min_size_bytes: typing.Optional[int] = None,
        max_size_bytes: typing.Optional[int] = None,
        created_after: typing.Optional[dt.datetime] = None,
        created_before: typing.Optional[dt.datetime] = None,
        sort: typing.Optional[FilesListRequestSort] = None,
        order: typing.Optional[FilesListRequestOrder] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> FileListResponse:
        """
        Returns one page of the org's file library, newest first, with the org's standing usage against its storage quota. Every file carries its source (upload or capture) and, for a capture, its surface and capture state. Filter with source, surface and session_id. Files persist until deleted and any ready file can be delivered to a phone the org holds.

        Parameters
        ----------
        limit : typing.Optional[int]
            max items per page

        offset : typing.Optional[int]
            pagination offset

        q : typing.Optional[str]
            filter by filename, case-insensitive substring match

        source : typing.Optional[FilesListRequestSource]
            only files of this source

        surface : typing.Optional[FilesListRequestSurface]
            only captures off this surface

        session_id : typing.Optional[str]
            only files captured by this session

        mime_type : typing.Optional[str]
            only files of exactly this media type

        min_size_bytes : typing.Optional[int]
            only files at least this many bytes (0 = no bound)

        max_size_bytes : typing.Optional[int]
            only files at most this many bytes (0 = no bound)

        created_after : typing.Optional[dt.datetime]
            only files registered at or after this time (RFC 3339)

        created_before : typing.Optional[dt.datetime]
            only files registered at or before this time (RFC 3339)

        sort : typing.Optional[FilesListRequestSort]
            field to sort by; source groups uploads and captures

        order : typing.Optional[FilesListRequestOrder]
            sort direction

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        FileListResponse
            OK

        Examples
        --------
        from axilio import AxilioApi

        client = AxilioApi(
            api_key="YOUR_API_KEY",
        )
        client.files.list()
        """
        _response = self._raw_client.list(
            limit=limit,
            offset=offset,
            q=q,
            source=source,
            surface=surface,
            session_id=session_id,
            mime_type=mime_type,
            min_size_bytes=min_size_bytes,
            max_size_bytes=max_size_bytes,
            created_after=created_after,
            created_before=created_before,
            sort=sort,
            order=order,
            request_options=request_options,
        )
        return _response.data

    def create(
        self, *, filename: str, mime_type: str, size_bytes: int, request_options: typing.Optional[RequestOptions] = None
    ) -> FileUploadResponse:
        """
        Registers an image or video in the org's file library and returns a presigned S3 URL to upload the bytes to. PUT the raw file to upload_url with the declared Content-Type and Content-Length headers before the URL expires, then call the complete endpoint to make it ready. The registered file has source=upload. Uploads are capped per file and per org by total size.

        Parameters
        ----------
        filename : str
            Display name for the file (also its name on the phone).

        mime_type : str
            MIME type of the upload; must be an allowed image or video type.

        size_bytes : int
            Exact size of the upload in bytes, up to 1 GiB; the presigned URL pins it.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        FileUploadResponse
            Created

        Examples
        --------
        from axilio import AxilioApi

        client = AxilioApi(
            api_key="YOUR_API_KEY",
        )
        client.files.create(
            filename="filename",
            mime_type="mime_type",
            size_bytes=1000000,
        )
        """
        _response = self._raw_client.create(
            filename=filename, mime_type=mime_type, size_bytes=size_bytes, request_options=request_options
        )
        return _response.data

    def delete(self, file_id: str, *, request_options: typing.Optional[RequestOptions] = None) -> DeleteFileOutputBody:
        """
        Removes a file from the org's library and everywhere it was delivered: the stored object and the library entry go immediately, and every phone holding a copy is scheduled to remove it (removal is confirmed per phone and retried until it lands). The response reports how many phones that recall reaches. This runs the same for an uploaded or a captured file; a capture's source phone keeps its own session copy, which belongs to the session, not the library.

        Parameters
        ----------
        file_id : str
            file identifier to delete

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        DeleteFileOutputBody
            OK

        Examples
        --------
        from axilio import AxilioApi

        client = AxilioApi(
            api_key="YOUR_API_KEY",
        )
        client.files.delete(
            file_id="file_id",
        )
        """
        _response = self._raw_client.delete(file_id, request_options=request_options)
        return _response.data

    def rename(
        self, file_id: str, *, filename: str, request_options: typing.Optional[RequestOptions] = None
    ) -> RenameFileOutputBody:
        """
        Updates the file's display name. Metadata only: storage is keyed by id, so the object never moves and existing URLs keep working, and past deliveries keep the name they were sent under. Only an uploaded file can be renamed; a captured file's name is part of its provenance, so renaming one is rejected.

        Parameters
        ----------
        file_id : str
            file identifier to rename

        filename : str
            New display name for the file.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        RenameFileOutputBody
            OK

        Examples
        --------
        from axilio import AxilioApi

        client = AxilioApi(
            api_key="YOUR_API_KEY",
        )
        client.files.rename(
            file_id="file_id",
            filename="filename",
        )
        """
        _response = self._raw_client.rename(file_id, filename=filename, request_options=request_options)
        return _response.data

    def complete(
        self, file_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> CompleteFileOutputBody:
        """
        Call after PUTting the bytes to the upload URL. Verifies the object landed at the declared size and type, checks the content really is the media it claims to be, and moves the file to ready so it can be delivered. Idempotent: completing an already-ready file just returns it. Applies to source=upload files; a captured file finalizes on its own from the phone's report.

        Parameters
        ----------
        file_id : str
            file identifier to finalize

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CompleteFileOutputBody
            OK

        Examples
        --------
        from axilio import AxilioApi

        client = AxilioApi(
            api_key="YOUR_API_KEY",
        )
        client.files.complete(
            file_id="file_id",
        )
        """
        _response = self._raw_client.complete(file_id, request_options=request_options)
        return _response.data

    def phones_session_files(
        self,
        session_id: str,
        *,
        limit: typing.Optional[int] = None,
        offset: typing.Optional[int] = None,
        q: typing.Optional[str] = None,
        mime_type: typing.Optional[str] = None,
        min_size_bytes: typing.Optional[int] = None,
        max_size_bytes: typing.Optional[int] = None,
        created_after: typing.Optional[dt.datetime] = None,
        created_before: typing.Optional[dt.datetime] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> FileListResponse:
        """
        Returns the files this session captured off its phone, newest first — the direct answer to "what did this session capture". Every row is source=capture. Rows appear at detection, before the bytes finish moving, so a caller waiting on a file watches its capture state progress rather than an empty list.

        Parameters
        ----------
        session_id : str
            session whose captures to list

        limit : typing.Optional[int]
            max items per page

        offset : typing.Optional[int]
            pagination offset

        q : typing.Optional[str]
            filter by filename, case-insensitive substring match

        mime_type : typing.Optional[str]
            only files of exactly this media type

        min_size_bytes : typing.Optional[int]
            only files at least this many bytes (0 = no bound)

        max_size_bytes : typing.Optional[int]
            only files at most this many bytes (0 = no bound)

        created_after : typing.Optional[dt.datetime]
            only files registered at or after this time (RFC 3339)

        created_before : typing.Optional[dt.datetime]
            only files registered at or before this time (RFC 3339)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        FileListResponse
            OK

        Examples
        --------
        from axilio import AxilioApi

        client = AxilioApi(
            api_key="YOUR_API_KEY",
        )
        client.files.phones_session_files(
            session_id="session_id",
        )
        """
        _response = self._raw_client.phones_session_files(
            session_id,
            limit=limit,
            offset=offset,
            q=q,
            mime_type=mime_type,
            min_size_bytes=min_size_bytes,
            max_size_bytes=max_size_bytes,
            created_after=created_after,
            created_before=created_before,
            request_options=request_options,
        )
        return _response.data


class AsyncFilesClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawFilesClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawFilesClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawFilesClient
        """
        return self._raw_client

    async def list(
        self,
        *,
        limit: typing.Optional[int] = None,
        offset: typing.Optional[int] = None,
        q: typing.Optional[str] = None,
        source: typing.Optional[FilesListRequestSource] = None,
        surface: typing.Optional[FilesListRequestSurface] = None,
        session_id: typing.Optional[str] = None,
        mime_type: typing.Optional[str] = None,
        min_size_bytes: typing.Optional[int] = None,
        max_size_bytes: typing.Optional[int] = None,
        created_after: typing.Optional[dt.datetime] = None,
        created_before: typing.Optional[dt.datetime] = None,
        sort: typing.Optional[FilesListRequestSort] = None,
        order: typing.Optional[FilesListRequestOrder] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> FileListResponse:
        """
        Returns one page of the org's file library, newest first, with the org's standing usage against its storage quota. Every file carries its source (upload or capture) and, for a capture, its surface and capture state. Filter with source, surface and session_id. Files persist until deleted and any ready file can be delivered to a phone the org holds.

        Parameters
        ----------
        limit : typing.Optional[int]
            max items per page

        offset : typing.Optional[int]
            pagination offset

        q : typing.Optional[str]
            filter by filename, case-insensitive substring match

        source : typing.Optional[FilesListRequestSource]
            only files of this source

        surface : typing.Optional[FilesListRequestSurface]
            only captures off this surface

        session_id : typing.Optional[str]
            only files captured by this session

        mime_type : typing.Optional[str]
            only files of exactly this media type

        min_size_bytes : typing.Optional[int]
            only files at least this many bytes (0 = no bound)

        max_size_bytes : typing.Optional[int]
            only files at most this many bytes (0 = no bound)

        created_after : typing.Optional[dt.datetime]
            only files registered at or after this time (RFC 3339)

        created_before : typing.Optional[dt.datetime]
            only files registered at or before this time (RFC 3339)

        sort : typing.Optional[FilesListRequestSort]
            field to sort by; source groups uploads and captures

        order : typing.Optional[FilesListRequestOrder]
            sort direction

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        FileListResponse
            OK

        Examples
        --------
        import asyncio

        from axilio import AsyncAxilioApi

        client = AsyncAxilioApi(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.files.list()


        asyncio.run(main())
        """
        _response = await self._raw_client.list(
            limit=limit,
            offset=offset,
            q=q,
            source=source,
            surface=surface,
            session_id=session_id,
            mime_type=mime_type,
            min_size_bytes=min_size_bytes,
            max_size_bytes=max_size_bytes,
            created_after=created_after,
            created_before=created_before,
            sort=sort,
            order=order,
            request_options=request_options,
        )
        return _response.data

    async def create(
        self, *, filename: str, mime_type: str, size_bytes: int, request_options: typing.Optional[RequestOptions] = None
    ) -> FileUploadResponse:
        """
        Registers an image or video in the org's file library and returns a presigned S3 URL to upload the bytes to. PUT the raw file to upload_url with the declared Content-Type and Content-Length headers before the URL expires, then call the complete endpoint to make it ready. The registered file has source=upload. Uploads are capped per file and per org by total size.

        Parameters
        ----------
        filename : str
            Display name for the file (also its name on the phone).

        mime_type : str
            MIME type of the upload; must be an allowed image or video type.

        size_bytes : int
            Exact size of the upload in bytes, up to 1 GiB; the presigned URL pins it.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        FileUploadResponse
            Created

        Examples
        --------
        import asyncio

        from axilio import AsyncAxilioApi

        client = AsyncAxilioApi(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.files.create(
                filename="filename",
                mime_type="mime_type",
                size_bytes=1000000,
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create(
            filename=filename, mime_type=mime_type, size_bytes=size_bytes, request_options=request_options
        )
        return _response.data

    async def delete(
        self, file_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> DeleteFileOutputBody:
        """
        Removes a file from the org's library and everywhere it was delivered: the stored object and the library entry go immediately, and every phone holding a copy is scheduled to remove it (removal is confirmed per phone and retried until it lands). The response reports how many phones that recall reaches. This runs the same for an uploaded or a captured file; a capture's source phone keeps its own session copy, which belongs to the session, not the library.

        Parameters
        ----------
        file_id : str
            file identifier to delete

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        DeleteFileOutputBody
            OK

        Examples
        --------
        import asyncio

        from axilio import AsyncAxilioApi

        client = AsyncAxilioApi(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.files.delete(
                file_id="file_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.delete(file_id, request_options=request_options)
        return _response.data

    async def rename(
        self, file_id: str, *, filename: str, request_options: typing.Optional[RequestOptions] = None
    ) -> RenameFileOutputBody:
        """
        Updates the file's display name. Metadata only: storage is keyed by id, so the object never moves and existing URLs keep working, and past deliveries keep the name they were sent under. Only an uploaded file can be renamed; a captured file's name is part of its provenance, so renaming one is rejected.

        Parameters
        ----------
        file_id : str
            file identifier to rename

        filename : str
            New display name for the file.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        RenameFileOutputBody
            OK

        Examples
        --------
        import asyncio

        from axilio import AsyncAxilioApi

        client = AsyncAxilioApi(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.files.rename(
                file_id="file_id",
                filename="filename",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.rename(file_id, filename=filename, request_options=request_options)
        return _response.data

    async def complete(
        self, file_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> CompleteFileOutputBody:
        """
        Call after PUTting the bytes to the upload URL. Verifies the object landed at the declared size and type, checks the content really is the media it claims to be, and moves the file to ready so it can be delivered. Idempotent: completing an already-ready file just returns it. Applies to source=upload files; a captured file finalizes on its own from the phone's report.

        Parameters
        ----------
        file_id : str
            file identifier to finalize

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CompleteFileOutputBody
            OK

        Examples
        --------
        import asyncio

        from axilio import AsyncAxilioApi

        client = AsyncAxilioApi(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.files.complete(
                file_id="file_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.complete(file_id, request_options=request_options)
        return _response.data

    async def phones_session_files(
        self,
        session_id: str,
        *,
        limit: typing.Optional[int] = None,
        offset: typing.Optional[int] = None,
        q: typing.Optional[str] = None,
        mime_type: typing.Optional[str] = None,
        min_size_bytes: typing.Optional[int] = None,
        max_size_bytes: typing.Optional[int] = None,
        created_after: typing.Optional[dt.datetime] = None,
        created_before: typing.Optional[dt.datetime] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> FileListResponse:
        """
        Returns the files this session captured off its phone, newest first — the direct answer to "what did this session capture". Every row is source=capture. Rows appear at detection, before the bytes finish moving, so a caller waiting on a file watches its capture state progress rather than an empty list.

        Parameters
        ----------
        session_id : str
            session whose captures to list

        limit : typing.Optional[int]
            max items per page

        offset : typing.Optional[int]
            pagination offset

        q : typing.Optional[str]
            filter by filename, case-insensitive substring match

        mime_type : typing.Optional[str]
            only files of exactly this media type

        min_size_bytes : typing.Optional[int]
            only files at least this many bytes (0 = no bound)

        max_size_bytes : typing.Optional[int]
            only files at most this many bytes (0 = no bound)

        created_after : typing.Optional[dt.datetime]
            only files registered at or after this time (RFC 3339)

        created_before : typing.Optional[dt.datetime]
            only files registered at or before this time (RFC 3339)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        FileListResponse
            OK

        Examples
        --------
        import asyncio

        from axilio import AsyncAxilioApi

        client = AsyncAxilioApi(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.files.phones_session_files(
                session_id="session_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.phones_session_files(
            session_id,
            limit=limit,
            offset=offset,
            q=q,
            mime_type=mime_type,
            min_size_bytes=min_size_bytes,
            max_size_bytes=max_size_bytes,
            created_after=created_after,
            created_before=created_before,
            request_options=request_options,
        )
        return _response.data
