# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.delete_file_output_body import DeleteFileOutputBody
from ..types.file_list_response import FileListResponse
from ..types.file_upload_response import FileUploadResponse
from .raw_client import AsyncRawFilesClient, RawFilesClient

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class FilesClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawFilesClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawFilesClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawFilesClient
        """
        return self._raw_client

    def list(
        self,
        *,
        limit: typing.Optional[int] = None,
        offset: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> FileListResponse:
        """
        Returns one page of the org's uploaded files, newest first. Files persist until deleted and can be pushed to any phone the org holds.

        Parameters
        ----------
        limit : typing.Optional[int]
            max items per page

        offset : typing.Optional[int]
            pagination offset

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        FileListResponse
            OK

        Examples
        --------
        from axilio import AxilioApi

        client = AxilioApi(
            api_key="YOUR_API_KEY",
        )
        client.files.list()
        """
        _response = self._raw_client.list(limit=limit, offset=offset, request_options=request_options)
        return _response.data

    def create(
        self, *, filename: str, mime_type: str, size_bytes: int, request_options: typing.Optional[RequestOptions] = None
    ) -> FileUploadResponse:
        """
        Registers an image or video in the org's file library and returns a presigned S3 URL to upload the bytes to. PUT the raw file to upload_url with the declared Content-Type and Content-Length headers before the URL expires. The file becomes pushable to phones once uploaded; the first push verifies the object. Uploads are capped per file by media type and per org by count and total size.

        Parameters
        ----------
        filename : str
            Display name for the file (also its name on the phone).

        mime_type : str
            MIME type of the upload; must be an allowed image or video type.

        size_bytes : int
            Exact size of the upload in bytes; the presigned URL pins it.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        FileUploadResponse
            Created

        Examples
        --------
        from axilio import AxilioApi

        client = AxilioApi(
            api_key="YOUR_API_KEY",
        )
        client.files.create(
            filename="filename",
            mime_type="mime_type",
            size_bytes=1000000,
        )
        """
        _response = self._raw_client.create(
            filename=filename, mime_type=mime_type, size_bytes=size_bytes, request_options=request_options
        )
        return _response.data

    def delete(self, file_id: str, *, request_options: typing.Optional[RequestOptions] = None) -> DeleteFileOutputBody:
        """
        Removes a file from the org's library: the stored object and the library entry, including its delivery history. Copies already delivered to phones are not affected (they are wiped when the phone is released).

        Parameters
        ----------
        file_id : str
            file identifier to delete

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        DeleteFileOutputBody
            OK

        Examples
        --------
        from axilio import AxilioApi

        client = AxilioApi(
            api_key="YOUR_API_KEY",
        )
        client.files.delete(
            file_id="file_id",
        )
        """
        _response = self._raw_client.delete(file_id, request_options=request_options)
        return _response.data


class AsyncFilesClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawFilesClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawFilesClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawFilesClient
        """
        return self._raw_client

    async def list(
        self,
        *,
        limit: typing.Optional[int] = None,
        offset: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> FileListResponse:
        """
        Returns one page of the org's uploaded files, newest first. Files persist until deleted and can be pushed to any phone the org holds.

        Parameters
        ----------
        limit : typing.Optional[int]
            max items per page

        offset : typing.Optional[int]
            pagination offset

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        FileListResponse
            OK

        Examples
        --------
        import asyncio

        from axilio import AsyncAxilioApi

        client = AsyncAxilioApi(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.files.list()


        asyncio.run(main())
        """
        _response = await self._raw_client.list(limit=limit, offset=offset, request_options=request_options)
        return _response.data

    async def create(
        self, *, filename: str, mime_type: str, size_bytes: int, request_options: typing.Optional[RequestOptions] = None
    ) -> FileUploadResponse:
        """
        Registers an image or video in the org's file library and returns a presigned S3 URL to upload the bytes to. PUT the raw file to upload_url with the declared Content-Type and Content-Length headers before the URL expires. The file becomes pushable to phones once uploaded; the first push verifies the object. Uploads are capped per file by media type and per org by count and total size.

        Parameters
        ----------
        filename : str
            Display name for the file (also its name on the phone).

        mime_type : str
            MIME type of the upload; must be an allowed image or video type.

        size_bytes : int
            Exact size of the upload in bytes; the presigned URL pins it.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        FileUploadResponse
            Created

        Examples
        --------
        import asyncio

        from axilio import AsyncAxilioApi

        client = AsyncAxilioApi(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.files.create(
                filename="filename",
                mime_type="mime_type",
                size_bytes=1000000,
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create(
            filename=filename, mime_type=mime_type, size_bytes=size_bytes, request_options=request_options
        )
        return _response.data

    async def delete(
        self, file_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> DeleteFileOutputBody:
        """
        Removes a file from the org's library: the stored object and the library entry, including its delivery history. Copies already delivered to phones are not affected (they are wiped when the phone is released).

        Parameters
        ----------
        file_id : str
            file identifier to delete

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        DeleteFileOutputBody
            OK

        Examples
        --------
        import asyncio

        from axilio import AsyncAxilioApi

        client = AsyncAxilioApi(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.files.delete(
                file_id="file_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.delete(file_id, request_options=request_options)
        return _response.data
