"""Generate the DCP typed wire layer from the vendored AsyncAPI contract.

Reads ``contracts/dcp-asyncapi.yaml`` (the public DCP contract the backend
publishes on every production deploy) and writes
``src/axilio/drivers/mobile/_wire.py``: the command-method names, the error-kind
taxonomy with its (code, retryable) specs, and one dataclass per params/result
schema. The models come from datamodel-code-generator; the constants are emitted
directly from the contract's command messages and ``x-dcp-error-table``.

The point is that this layer can never drift from the deployed protocol by hand:
the backend's own drift gate forces the contract to equal the Go server, and
``tests/test_dcp_wire_drift.py`` forces this file to equal the contract. Run
this after the vendored contract changes:

    python scripts/generate_dcp_wire.py
"""

from __future__ import annotations

import json
import pathlib
import re
import subprocess
import tempfile

import yaml

REPO = pathlib.Path(__file__).resolve().parent.parent
CONTRACT = REPO / "contracts" / "dcp-asyncapi.yaml"
OUT = REPO / "src" / "axilio" / "drivers" / "mobile" / "_wire.py"


def const(name: str) -> str:
    """"Touch.longPress" / "UnknownOp" -> "TOUCH_LONG_PRESS" / "UNKNOWN_OP"."""
    s = name.replace(".", "_")
    s = re.sub(r"(?<=[a-z0-9])(?=[A-Z])", "_", s)
    return s.upper()


def generate_models(schemas: dict) -> str:
    """Emit one dataclass per components.schema via datamodel-code-generator."""
    doc = json.dumps({"$defs": schemas}).replace("#/components/schemas/", "#/$defs/")
    with tempfile.TemporaryDirectory() as tmp:
        schema_path = pathlib.Path(tmp) / "schemas.json"
        models_path = pathlib.Path(tmp) / "models.py"
        schema_path.write_text(doc)
        subprocess.run(
            [
                "uvx",
                "--from",
                "datamodel-code-generator",
                "datamodel-codegen",
                "--input",
                str(schema_path),
                "--input-file-type",
                "jsonschema",
                "--output",
                str(models_path),
                "--output-model-type",
                "dataclasses.dataclass",
                "--use-standard-collections",
                "--target-python-version",
                "3.10",
                "--formatters",
                "black",
            ],
            check=True,
            capture_output=True,
        )
        src = models_path.read_text()
    keep = []
    for line in src.splitlines():
        # Drop the generator's header and every import — the emitted module
        # supplies its own single `from dataclasses import dataclass`.
        if line.startswith(("# generated by datamodel-codegen", "#   ", "from ", "import ")):
            continue
        if line.startswith("Model:"):
            continue
        keep.append(line)
    return "\n".join(keep).strip()


def main() -> None:
    doc = yaml.safe_load(CONTRACT.read_text())
    methods = sorted(
        name
        for name, m in doc["components"]["messages"].items()
        if m.get("x-dcp-kind") == "command"
    )
    errtab = doc.get("x-dcp-error-table", {})
    models = generate_models(doc["components"]["schemas"])

    out: list[str] = []
    out.append('"""Generated DCP wire layer - DO NOT EDIT.')
    out.append("")
    out.append("Regenerate with `python scripts/generate_dcp_wire.py`. The source of truth is")
    out.append("the DCP AsyncAPI contract vendored at contracts/dcp-asyncapi.yaml, which the")
    out.append("backend publishes on every production deploy. tests/test_dcp_wire_drift.py")
    out.append("asserts this file equals that contract, so the typed layer can never fall out")
    out.append('of step with the deployed protocol."""')
    out.append("")
    out.append("from __future__ import annotations")
    out.append("")
    out.append("from dataclasses import dataclass")
    if "TypeAlias" in models:
        out.append("from typing import TypeAlias")
    out.append("")
    out.append(f"PROTOCOL_VERSION = {doc['info'].get('x-dcp-protocol-version')!r}")
    out.append("")
    out.append("# --- command methods (Domain.method wire names) ---")
    for meth in methods:
        out.append(f'METHOD_{const(meth)} = "{meth}"')
    out.append("")
    out.append("# --- error kinds + their (code, retryable) specs ---")
    for kind in errtab:
        out.append(f'KIND_{const(kind)} = "{kind}"')
    out.append("")
    out.append("ERROR_SPECS: dict[str, tuple[int, bool]] = {")
    for kind, spec in errtab.items():
        out.append(f'    "{kind}": ({spec["code"]}, {bool(spec["retryable"])}),')
    out.append("}")
    out.append("")
    out.append("# --- params / result models (one per contract schema) ---")
    out.append("")
    out.append(models)
    out.append("")
    OUT.write_text("\n".join(out))
    # Format with the repo's pinned black so the committed file is stable and a
    # regeneration never trips `black --check` in CI.
    subprocess.run(["black", "--quiet", str(OUT)], check=True)
    print(f"wrote {OUT.relative_to(REPO)}: {len(methods)} methods, {len(errtab)} kinds")


if __name__ == "__main__":
    main()
