# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.billing_history_response import BillingHistoryResponse
from ..types.phone_rental_subscription_list_response import PhoneRentalSubscriptionListResponse
from ..types.subscription_auto_recharge_settings_response import SubscriptionAutoRechargeSettingsResponse
from ..types.subscription_balance_response import SubscriptionBalanceResponse
from ..types.subscription_response import SubscriptionResponse
from .raw_client import AsyncRawBillingClient, RawBillingClient


class BillingClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawBillingClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawBillingClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawBillingClient
        """
        return self._raw_client

    def get_auto_recharge(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> SubscriptionAutoRechargeSettingsResponse:
        """
        Returns the organization's automatic balance top-up configuration and status.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SubscriptionAutoRechargeSettingsResponse
            OK

        Examples
        --------
        from axilio import AxilioApi

        client = AxilioApi(
            api_key="YOUR_API_KEY",
        )
        client.billing.get_auto_recharge()
        """
        _response = self._raw_client.get_auto_recharge(request_options=request_options)
        return _response.data

    def get_balance(self, *, request_options: typing.Optional[RequestOptions] = None) -> SubscriptionBalanceResponse:
        """
        Returns the organization's current credit balance in microdollars plus a display string.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SubscriptionBalanceResponse
            OK

        Examples
        --------
        from axilio import AxilioApi

        client = AxilioApi(
            api_key="YOUR_API_KEY",
        )
        client.billing.get_balance()
        """
        _response = self._raw_client.get_balance(request_options=request_options)
        return _response.data

    def get_history(
        self,
        *,
        limit: typing.Optional[int] = None,
        offset: typing.Optional[int] = None,
        search: typing.Optional[str] = None,
        billing_cycle: typing.Optional[str] = None,
        sort_by: typing.Optional[str] = None,
        sort_order: typing.Optional[str] = None,
        status: typing.Optional[str] = None,
        date_from: typing.Optional[str] = None,
        date_to: typing.Optional[str] = None,
        plan_name: typing.Optional[str] = None,
        phone_id: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> BillingHistoryResponse:
        """
        Paginated invoice history for the caller's organization with optional filters and sort.

        Parameters
        ----------
        limit : typing.Optional[int]
            max items per page

        offset : typing.Optional[int]
            pagination offset

        search : typing.Optional[str]
            free-text search across invoice number/description

        billing_cycle : typing.Optional[str]
            filter by billing cycle

        sort_by : typing.Optional[str]
            column to sort by

        sort_order : typing.Optional[str]
            asc or desc

        status : typing.Optional[str]
            invoice status filter (lowercase)

        date_from : typing.Optional[str]
            RFC3339 lower bound for invoice_date

        date_to : typing.Optional[str]
            RFC3339 upper bound for invoice_date (with date_from = an exact calendar month)

        plan_name : typing.Optional[str]
            filter by plan name

        phone_id : typing.Optional[str]
            filter to invoices for a dedicated phone

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        BillingHistoryResponse
            OK

        Examples
        --------
        from axilio import AxilioApi

        client = AxilioApi(
            api_key="YOUR_API_KEY",
        )
        client.billing.get_history()
        """
        _response = self._raw_client.get_history(
            limit=limit,
            offset=offset,
            search=search,
            billing_cycle=billing_cycle,
            sort_by=sort_by,
            sort_order=sort_order,
            status=status,
            date_from=date_from,
            date_to=date_to,
            plan_name=plan_name,
            phone_id=phone_id,
            request_options=request_options,
        )
        return _response.data

    def get_rental_subscriptions(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> PhoneRentalSubscriptionListResponse:
        """
        Returns every active and pending phone rental subscription owned by the caller's organization.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PhoneRentalSubscriptionListResponse
            OK

        Examples
        --------
        from axilio import AxilioApi

        client = AxilioApi(
            api_key="YOUR_API_KEY",
        )
        client.billing.get_rental_subscriptions()
        """
        _response = self._raw_client.get_rental_subscriptions(request_options=request_options)
        return _response.data

    def get_subscription(self, *, request_options: typing.Optional[RequestOptions] = None) -> SubscriptionResponse:
        """
        Returns the caller organization's current plan.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SubscriptionResponse
            OK

        Examples
        --------
        from axilio import AxilioApi

        client = AxilioApi(
            api_key="YOUR_API_KEY",
        )
        client.billing.get_subscription()
        """
        _response = self._raw_client.get_subscription(request_options=request_options)
        return _response.data


class AsyncBillingClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawBillingClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawBillingClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawBillingClient
        """
        return self._raw_client

    async def get_auto_recharge(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> SubscriptionAutoRechargeSettingsResponse:
        """
        Returns the organization's automatic balance top-up configuration and status.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SubscriptionAutoRechargeSettingsResponse
            OK

        Examples
        --------
        import asyncio

        from axilio import AsyncAxilioApi

        client = AsyncAxilioApi(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.billing.get_auto_recharge()


        asyncio.run(main())
        """
        _response = await self._raw_client.get_auto_recharge(request_options=request_options)
        return _response.data

    async def get_balance(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> SubscriptionBalanceResponse:
        """
        Returns the organization's current credit balance in microdollars plus a display string.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SubscriptionBalanceResponse
            OK

        Examples
        --------
        import asyncio

        from axilio import AsyncAxilioApi

        client = AsyncAxilioApi(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.billing.get_balance()


        asyncio.run(main())
        """
        _response = await self._raw_client.get_balance(request_options=request_options)
        return _response.data

    async def get_history(
        self,
        *,
        limit: typing.Optional[int] = None,
        offset: typing.Optional[int] = None,
        search: typing.Optional[str] = None,
        billing_cycle: typing.Optional[str] = None,
        sort_by: typing.Optional[str] = None,
        sort_order: typing.Optional[str] = None,
        status: typing.Optional[str] = None,
        date_from: typing.Optional[str] = None,
        date_to: typing.Optional[str] = None,
        plan_name: typing.Optional[str] = None,
        phone_id: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> BillingHistoryResponse:
        """
        Paginated invoice history for the caller's organization with optional filters and sort.

        Parameters
        ----------
        limit : typing.Optional[int]
            max items per page

        offset : typing.Optional[int]
            pagination offset

        search : typing.Optional[str]
            free-text search across invoice number/description

        billing_cycle : typing.Optional[str]
            filter by billing cycle

        sort_by : typing.Optional[str]
            column to sort by

        sort_order : typing.Optional[str]
            asc or desc

        status : typing.Optional[str]
            invoice status filter (lowercase)

        date_from : typing.Optional[str]
            RFC3339 lower bound for invoice_date

        date_to : typing.Optional[str]
            RFC3339 upper bound for invoice_date (with date_from = an exact calendar month)

        plan_name : typing.Optional[str]
            filter by plan name

        phone_id : typing.Optional[str]
            filter to invoices for a dedicated phone

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        BillingHistoryResponse
            OK

        Examples
        --------
        import asyncio

        from axilio import AsyncAxilioApi

        client = AsyncAxilioApi(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.billing.get_history()


        asyncio.run(main())
        """
        _response = await self._raw_client.get_history(
            limit=limit,
            offset=offset,
            search=search,
            billing_cycle=billing_cycle,
            sort_by=sort_by,
            sort_order=sort_order,
            status=status,
            date_from=date_from,
            date_to=date_to,
            plan_name=plan_name,
            phone_id=phone_id,
            request_options=request_options,
        )
        return _response.data

    async def get_rental_subscriptions(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> PhoneRentalSubscriptionListResponse:
        """
        Returns every active and pending phone rental subscription owned by the caller's organization.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PhoneRentalSubscriptionListResponse
            OK

        Examples
        --------
        import asyncio

        from axilio import AsyncAxilioApi

        client = AsyncAxilioApi(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.billing.get_rental_subscriptions()


        asyncio.run(main())
        """
        _response = await self._raw_client.get_rental_subscriptions(request_options=request_options)
        return _response.data

    async def get_subscription(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> SubscriptionResponse:
        """
        Returns the caller organization's current plan.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SubscriptionResponse
            OK

        Examples
        --------
        import asyncio

        from axilio import AsyncAxilioApi

        client = AsyncAxilioApi(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.billing.get_subscription()


        asyncio.run(main())
        """
        _response = await self._raw_client.get_subscription(request_options=request_options)
        return _response.data
