# This file was auto-generated by Fern from our API Definition.

import typing
from json.decoder import JSONDecodeError

from ..core.api_error import ApiError
from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.http_response import AsyncHttpResponse, HttpResponse
from ..core.parse_error import ParsingError
from ..core.pydantic_utilities import parse_obj_as
from ..core.request_options import RequestOptions
from ..types.billing_history_response import BillingHistoryResponse
from ..types.phone_rental_subscription_list_response import PhoneRentalSubscriptionListResponse
from ..types.subscription_auto_recharge_settings_response import SubscriptionAutoRechargeSettingsResponse
from ..types.subscription_balance_response import SubscriptionBalanceResponse
from ..types.subscription_response import SubscriptionResponse
from pydantic import ValidationError


class RawBillingClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._client_wrapper = client_wrapper

    def get_auto_recharge(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[SubscriptionAutoRechargeSettingsResponse]:
        """
        Returns the organization's automatic balance top-up configuration and status.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[SubscriptionAutoRechargeSettingsResponse]
            OK
        """
        _response = self._client_wrapper.httpx_client.request(
            "billing/auto-recharge",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    SubscriptionAutoRechargeSettingsResponse,
                    parse_obj_as(
                        type_=SubscriptionAutoRechargeSettingsResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def get_balance(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[SubscriptionBalanceResponse]:
        """
        Returns the organization's current credit balance in microdollars plus a display string.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[SubscriptionBalanceResponse]
            OK
        """
        _response = self._client_wrapper.httpx_client.request(
            "billing/balance",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    SubscriptionBalanceResponse,
                    parse_obj_as(
                        type_=SubscriptionBalanceResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def get_history(
        self,
        *,
        limit: typing.Optional[int] = None,
        offset: typing.Optional[int] = None,
        search: typing.Optional[str] = None,
        billing_cycle: typing.Optional[str] = None,
        sort_by: typing.Optional[str] = None,
        sort_order: typing.Optional[str] = None,
        status: typing.Optional[str] = None,
        date_from: typing.Optional[str] = None,
        date_to: typing.Optional[str] = None,
        plan_name: typing.Optional[str] = None,
        phone_id: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[BillingHistoryResponse]:
        """
        Paginated invoice history for the caller's organization with optional filters and sort.

        Parameters
        ----------
        limit : typing.Optional[int]
            max items per page

        offset : typing.Optional[int]
            pagination offset

        search : typing.Optional[str]
            free-text search across invoice number/description

        billing_cycle : typing.Optional[str]
            filter by billing cycle

        sort_by : typing.Optional[str]
            column to sort by

        sort_order : typing.Optional[str]
            asc or desc

        status : typing.Optional[str]
            invoice status filter (lowercase)

        date_from : typing.Optional[str]
            RFC3339 lower bound for invoice_date

        date_to : typing.Optional[str]
            RFC3339 upper bound for invoice_date (with date_from = an exact calendar month)

        plan_name : typing.Optional[str]
            filter by plan name

        phone_id : typing.Optional[str]
            filter to invoices for a dedicated phone

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[BillingHistoryResponse]
            OK
        """
        _response = self._client_wrapper.httpx_client.request(
            "billing/history",
            method="GET",
            params={
                "limit": limit,
                "offset": offset,
                "search": search,
                "billing_cycle": billing_cycle,
                "sort_by": sort_by,
                "sort_order": sort_order,
                "status": status,
                "date_from": date_from,
                "date_to": date_to,
                "plan_name": plan_name,
                "phone_id": phone_id,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    BillingHistoryResponse,
                    parse_obj_as(
                        type_=BillingHistoryResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def get_rental_subscriptions(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[PhoneRentalSubscriptionListResponse]:
        """
        Returns every phone rental subscription owned by the caller's organization, in any lifecycle state (active or canceled) - canceled rentals are included so past rentals stay visible. Each item's status field tells them apart. The summary block (active_count, combined monthly cost) counts only active rentals.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[PhoneRentalSubscriptionListResponse]
            OK
        """
        _response = self._client_wrapper.httpx_client.request(
            "billing/phone-rental-subscriptions",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    PhoneRentalSubscriptionListResponse,
                    parse_obj_as(
                        type_=PhoneRentalSubscriptionListResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def get_subscription(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[SubscriptionResponse]:
        """
        Returns the caller organization's active subscription plan. Only an active subscription is returned; if the org has none, this responds 404. (The status field is therefore always 'active' here.)

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[SubscriptionResponse]
            OK
        """
        _response = self._client_wrapper.httpx_client.request(
            "billing/subscription",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    SubscriptionResponse,
                    parse_obj_as(
                        type_=SubscriptionResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)


class AsyncRawBillingClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._client_wrapper = client_wrapper

    async def get_auto_recharge(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[SubscriptionAutoRechargeSettingsResponse]:
        """
        Returns the organization's automatic balance top-up configuration and status.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[SubscriptionAutoRechargeSettingsResponse]
            OK
        """
        _response = await self._client_wrapper.httpx_client.request(
            "billing/auto-recharge",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    SubscriptionAutoRechargeSettingsResponse,
                    parse_obj_as(
                        type_=SubscriptionAutoRechargeSettingsResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def get_balance(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[SubscriptionBalanceResponse]:
        """
        Returns the organization's current credit balance in microdollars plus a display string.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[SubscriptionBalanceResponse]
            OK
        """
        _response = await self._client_wrapper.httpx_client.request(
            "billing/balance",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    SubscriptionBalanceResponse,
                    parse_obj_as(
                        type_=SubscriptionBalanceResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def get_history(
        self,
        *,
        limit: typing.Optional[int] = None,
        offset: typing.Optional[int] = None,
        search: typing.Optional[str] = None,
        billing_cycle: typing.Optional[str] = None,
        sort_by: typing.Optional[str] = None,
        sort_order: typing.Optional[str] = None,
        status: typing.Optional[str] = None,
        date_from: typing.Optional[str] = None,
        date_to: typing.Optional[str] = None,
        plan_name: typing.Optional[str] = None,
        phone_id: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[BillingHistoryResponse]:
        """
        Paginated invoice history for the caller's organization with optional filters and sort.

        Parameters
        ----------
        limit : typing.Optional[int]
            max items per page

        offset : typing.Optional[int]
            pagination offset

        search : typing.Optional[str]
            free-text search across invoice number/description

        billing_cycle : typing.Optional[str]
            filter by billing cycle

        sort_by : typing.Optional[str]
            column to sort by

        sort_order : typing.Optional[str]
            asc or desc

        status : typing.Optional[str]
            invoice status filter (lowercase)

        date_from : typing.Optional[str]
            RFC3339 lower bound for invoice_date

        date_to : typing.Optional[str]
            RFC3339 upper bound for invoice_date (with date_from = an exact calendar month)

        plan_name : typing.Optional[str]
            filter by plan name

        phone_id : typing.Optional[str]
            filter to invoices for a dedicated phone

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[BillingHistoryResponse]
            OK
        """
        _response = await self._client_wrapper.httpx_client.request(
            "billing/history",
            method="GET",
            params={
                "limit": limit,
                "offset": offset,
                "search": search,
                "billing_cycle": billing_cycle,
                "sort_by": sort_by,
                "sort_order": sort_order,
                "status": status,
                "date_from": date_from,
                "date_to": date_to,
                "plan_name": plan_name,
                "phone_id": phone_id,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    BillingHistoryResponse,
                    parse_obj_as(
                        type_=BillingHistoryResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def get_rental_subscriptions(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[PhoneRentalSubscriptionListResponse]:
        """
        Returns every phone rental subscription owned by the caller's organization, in any lifecycle state (active or canceled) - canceled rentals are included so past rentals stay visible. Each item's status field tells them apart. The summary block (active_count, combined monthly cost) counts only active rentals.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[PhoneRentalSubscriptionListResponse]
            OK
        """
        _response = await self._client_wrapper.httpx_client.request(
            "billing/phone-rental-subscriptions",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    PhoneRentalSubscriptionListResponse,
                    parse_obj_as(
                        type_=PhoneRentalSubscriptionListResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def get_subscription(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[SubscriptionResponse]:
        """
        Returns the caller organization's active subscription plan. Only an active subscription is returned; if the org has none, this responds 404. (The status field is therefore always 'active' here.)

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[SubscriptionResponse]
            OK
        """
        _response = await self._client_wrapper.httpx_client.request(
            "billing/subscription",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    SubscriptionResponse,
                    parse_obj_as(
                        type_=SubscriptionResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)
