# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.accessibility_tree_locate_response import AccessibilityTreeLocateResponse
from ..types.accessibility_tree_node import AccessibilityTreeNode
from .raw_client import AsyncRawAccessibilityTreesClient, RawAccessibilityTreesClient

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class AccessibilityTreesClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawAccessibilityTreesClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawAccessibilityTreesClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawAccessibilityTreesClient
        """
        return self._raw_client

    def accessibility_trees_locate(
        self,
        *,
        nodes: typing.Sequence[AccessibilityTreeNode],
        query: str,
        image: typing.Optional[str] = OMIT,
        model: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AccessibilityTreeLocateResponse:
        """
        Find the node a query describes in an accessibility tree.

        Answers with one of the request's node ids, or not found; never a point.

        Parameters
        ----------
        nodes : typing.Sequence[AccessibilityTreeNode]
            Candidate nodes

        query : str
            Natural-language target description

        image : typing.Optional[str]
            Optional base64 screenshot (PNG or JPEG) the node bounds are in

        model : typing.Optional[str]
            VLM model to use; must be one of the models from GET /models. Omit to use the server's configured default.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AccessibilityTreeLocateResponse
            Successful Response

        Examples
        --------
        from axilio.argus import AccessibilityTreeNode, ArgusApi

        client = ArgusApi(
            api_key="YOUR_API_KEY",
            base_url="https://yourhost.com/path/to/api",
        )
        client.accessibility_trees.accessibility_trees_locate(
            nodes=[
                AccessibilityTreeNode(
                    node_id="node_id",
                    role="role",
                )
            ],
            query="query",
        )
        """
        _response = self._raw_client.accessibility_trees_locate(
            nodes=nodes, query=query, image=image, model=model, request_options=request_options
        )
        return _response.data


class AsyncAccessibilityTreesClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawAccessibilityTreesClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawAccessibilityTreesClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawAccessibilityTreesClient
        """
        return self._raw_client

    async def accessibility_trees_locate(
        self,
        *,
        nodes: typing.Sequence[AccessibilityTreeNode],
        query: str,
        image: typing.Optional[str] = OMIT,
        model: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AccessibilityTreeLocateResponse:
        """
        Find the node a query describes in an accessibility tree.

        Answers with one of the request's node ids, or not found; never a point.

        Parameters
        ----------
        nodes : typing.Sequence[AccessibilityTreeNode]
            Candidate nodes

        query : str
            Natural-language target description

        image : typing.Optional[str]
            Optional base64 screenshot (PNG or JPEG) the node bounds are in

        model : typing.Optional[str]
            VLM model to use; must be one of the models from GET /models. Omit to use the server's configured default.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AccessibilityTreeLocateResponse
            Successful Response

        Examples
        --------
        import asyncio

        from axilio.argus import AccessibilityTreeNode, AsyncArgusApi

        client = AsyncArgusApi(
            api_key="YOUR_API_KEY",
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.accessibility_trees.accessibility_trees_locate(
                nodes=[
                    AccessibilityTreeNode(
                        node_id="node_id",
                        role="role",
                    )
                ],
                query="query",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.accessibility_trees_locate(
            nodes=nodes, query=query, image=image, model=model, request_options=request_options
        )
        return _response.data
