# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.message_output_body import MessageOutputBody
from ..types.user_user_response import UserUserResponse
from .raw_client import AsyncRawUserClient, RawUserClient


class UserClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawUserClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawUserClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawUserClient
        """
        return self._raw_client

    def get_me(self, *, request_options: typing.Optional[RequestOptions] = None) -> UserUserResponse:
        """
        Returns the authenticated user's profile (id, email, verified/admin flags, timestamps).

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        UserUserResponse
            OK

        Examples
        --------
        from axilio import AxilioApi

        client = AxilioApi(
            api_key="YOUR_API_KEY",
        )
        client.user.get_me()
        """
        _response = self._raw_client.get_me(request_options=request_options)
        return _response.data

    def delete_me(self, *, request_options: typing.Optional[RequestOptions] = None) -> MessageOutputBody:
        """
        Deletes the caller's organizations (best-effort) then their user account. Account data cleanup happens asynchronously via identity-provider webhooks.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        MessageOutputBody
            OK

        Examples
        --------
        from axilio import AxilioApi

        client = AxilioApi(
            api_key="YOUR_API_KEY",
        )
        client.user.delete_me()
        """
        _response = self._raw_client.delete_me(request_options=request_options)
        return _response.data


class AsyncUserClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawUserClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawUserClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawUserClient
        """
        return self._raw_client

    async def get_me(self, *, request_options: typing.Optional[RequestOptions] = None) -> UserUserResponse:
        """
        Returns the authenticated user's profile (id, email, verified/admin flags, timestamps).

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        UserUserResponse
            OK

        Examples
        --------
        import asyncio

        from axilio import AsyncAxilioApi

        client = AsyncAxilioApi(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.user.get_me()


        asyncio.run(main())
        """
        _response = await self._raw_client.get_me(request_options=request_options)
        return _response.data

    async def delete_me(self, *, request_options: typing.Optional[RequestOptions] = None) -> MessageOutputBody:
        """
        Deletes the caller's organizations (best-effort) then their user account. Account data cleanup happens asynchronously via identity-provider webhooks.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        MessageOutputBody
            OK

        Examples
        --------
        import asyncio

        from axilio import AsyncAxilioApi

        client = AsyncAxilioApi(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.user.delete_me()


        asyncio.run(main())
        """
        _response = await self._raw_client.delete_me(request_options=request_options)
        return _response.data
