# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata


class ApiKeyRegenerateResponse(UniversalBaseModel):
    """
    Response returned when an API key is regenerated.
    """

    schema_: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="$schema"),
        pydantic.Field(alias="$schema", description="A URL to the JSON Schema for this object."),
    ] = None
    created_at: dt.datetime = pydantic.Field()
    """
    Timestamp when the key was originally created.
    """

    id: str = pydantic.Field()
    """
    API key identifier.
    """

    key_value: str = pydantic.Field()
    """
    New full plaintext key.
    """

    name: str = pydantic.Field()
    """
    Human-readable label for the key.
    """

    regenerated_at: dt.datetime = pydantic.Field()
    """
    Timestamp when the key was regenerated.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
