# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .file_summary_status import FileSummaryStatus


class FileSummary(UniversalBaseModel):
    """
    One file in the org's library.
    """

    created_at: dt.datetime = pydantic.Field()
    """
    When the upload was registered.
    """

    download_url: typing.Optional[str] = pydantic.Field(default=None)
    """
    Short-lived signed URL to read the file's bytes. Present only for ready files; re-list to refresh an expired one.
    """

    filename: str = pydantic.Field()
    """
    Original filename; used as the display name when the file lands on a phone.
    """

    id: str = pydantic.Field()
    """
    File identifier. Unique across uploads and downloads.
    """

    mime_type: str = pydantic.Field()
    """
    Declared MIME type, pinned by the presigned upload.
    """

    size_bytes: int = pydantic.Field()
    """
    Declared size in bytes, pinned by the presigned upload.
    """

    status: FileSummaryStatus = pydantic.Field()
    """
    uploading until the object is verified in storage, then ready. Complete an upload to move it to ready.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
