# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .phone_active_session_allocated_by import PhoneActiveSessionAllocatedBy
from .phone_active_session_phone_status import PhoneActiveSessionPhoneStatus
from .phone_active_session_phone_type import PhoneActiveSessionPhoneType


class PhoneActiveSession(UniversalBaseModel):
    """
    One active phone allocation for the dashboard overview: a phone currently claimed by a run, a workflow-less interactive lease, or a dedicated phone in use.
    """

    allocated_at: dt.datetime = pydantic.Field()
    """
    When the session claimed the phone.
    """

    allocated_by: typing.Optional[PhoneActiveSessionAllocatedBy] = pydantic.Field(default=None)
    """
    AllocatedBy identifies what triggered the allocation (WORKFLOW_EDITOR, DASHBOARD_RUN, API_RUN, INTERACTIVE).
    """

    is_dedicated_phone: bool = pydantic.Field()
    """
    True when the phone is a dedicated/rented phone.
    """

    location: typing.Optional[str] = pydantic.Field(default=None)
    """
    Rack/data-center the phone is pinned to.
    """

    model_name: typing.Optional[str] = pydantic.Field(default=None)
    """
    Phone's model, if known.
    """

    name: typing.Optional[str] = pydantic.Field(default=None)
    """
    Optional user-chosen session label; unique among the org's active sessions.
    """

    nickname: typing.Optional[str] = pydantic.Field(default=None)
    """
    Org's nickname for the phone, if set.
    """

    phone_id: str = pydantic.Field()
    """
    Phone claimed by the session.
    """

    phone_name: typing.Optional[str] = pydantic.Field(default=None)
    """
    Phone's name, if set.
    """

    phone_status: PhoneActiveSessionPhoneStatus = pydantic.Field()
    """
    Phone's lifecycle status (ACTIVE/INACTIVE/...).
    """

    phone_type: typing.Optional[PhoneActiveSessionPhoneType] = pydantic.Field(default=None)
    """
    IPHONE or ANDROID.
    """

    session_id: str = pydantic.Field()
    """
    Phone_sessions row id (the canonical session id).
    """

    tags: typing.Optional[typing.Dict[str, str]] = pydantic.Field(default=None)
    """
    Optional key->value labels attached to the session.
    """

    workflow_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    Workflow tied to the session, nil for an interactive lease.
    """

    workflow_name: typing.Optional[str] = pydantic.Field(default=None)
    """
    Tied workflow's name, nil for an interactive lease.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
