# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata


class PhoneLiveViewTokenResponse(UniversalBaseModel):
    """
    Live-view token mint response.
    """

    schema_: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="$schema"),
        pydantic.Field(alias="$schema", description="A URL to the JSON Schema for this object."),
    ] = None
    live_view_url: str = pydantic.Field()
    """
    Hosted live-view page URL embedding this token (live screen + interaction, iframe-embeddable). Bearer capability; treat as a secret. Dies with the session.
    """

    phone_id: str = pydantic.Field()
    """
    The session's phone.
    """

    session_id: str = pydantic.Field()
    """
    Session the token is scoped to.
    """

    token: str = pydantic.Field()
    """
    Allocation-scoped live-view token.
    """

    view_only: bool = pydantic.Field()
    """
    Whether the session's live view is watch-only.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
