# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class PhoneSessionListItem(UniversalBaseModel):
    allocated_at: str
    allocated_by: typing.Optional[str] = None
    deallocated_at: typing.Optional[str] = None
    duration_seconds: typing.Optional[int] = None
    is_dedicated_phone: bool
    location: typing.Optional[str] = None
    model_name: typing.Optional[str] = None
    nickname: typing.Optional[str] = None
    phone_id: str
    phone_name: typing.Optional[str] = None
    phone_type: typing.Optional[str] = None
    session_id: str
    source: str
    status: str
    workflow_id: typing.Optional[str] = None
    workflow_name: typing.Optional[str] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
