# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .phone_location_availability_entry import PhoneLocationAvailabilityEntry
from .phone_type_availability_entry import PhoneTypeAvailabilityEntry


class PhoneSharedAvailability(UniversalBaseModel):
    """
    Shared-pool availability summary.
    """

    available: int = pydantic.Field()
    """
    Shared phones free to allocate right now, across every type and location in the response.
    """

    by_location: typing.Optional[typing.List[PhoneLocationAvailabilityEntry]] = pydantic.Field(default=None)
    """
    Counts per active location; locations with zero shared phones still appear.
    """

    by_type: typing.Optional[typing.List[PhoneTypeAvailabilityEntry]] = pydantic.Field(default=None)
    """
    Counts per phone type.
    """

    total: int = pydantic.Field()
    """
    Active shared phones, across every type and location in the response.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
