# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class PhoneLocationAvailabilityEntry(UniversalBaseModel):
    """
    Shared-pool availability at a single location.
    """

    available: int = pydantic.Field()
    """
    Phones free to allocate at this location right now.
    """

    city: str = pydantic.Field()
    """
    City name for this location.
    """

    location: str = pydantic.Field()
    """
    Location slug identifier.
    """

    region: str = pydantic.Field()
    """
    Broader geographic region label.
    """

    state: str = pydantic.Field()
    """
    State or region name for this location.
    """

    total: int = pydantic.Field()
    """
    Active shared phones at this location.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
