# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .phone_session_detail_response_allocated_by import PhoneSessionDetailResponseAllocatedBy
from .phone_session_detail_response_phone_status import PhoneSessionDetailResponsePhoneStatus
from .phone_session_detail_response_phone_type import PhoneSessionDetailResponsePhoneType
from .phone_session_detail_response_recording_status import PhoneSessionDetailResponseRecordingStatus
from .phone_session_detail_response_source import PhoneSessionDetailResponseSource
from .phone_session_detail_response_status import PhoneSessionDetailResponseStatus


class PhoneSessionDetailResponse(UniversalBaseModel):
    """
    Detail for a single session: the session, phone display fields, and a recording URL when available.
    """

    schema_: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="$schema"),
        pydantic.Field(alias="$schema", description="A URL to the JSON Schema for this object."),
    ] = None
    allocated_at: dt.datetime = pydantic.Field()
    """
    When the session claimed the phone.
    """

    allocated_by: typing.Optional[PhoneSessionDetailResponseAllocatedBy] = pydantic.Field(default=None)
    """
    How the session was started.
    """

    deallocated_at: typing.Optional[dt.datetime] = pydantic.Field(default=None)
    """
    When the session released the phone; absent while active.
    """

    is_dedicated_phone: bool = pydantic.Field()
    """
    Whether the phone is a dedicated (rented) phone.
    """

    location: typing.Optional[str] = pydantic.Field(default=None)
    """
    Physical hosting location of the phone.
    """

    model_name: typing.Optional[str] = pydantic.Field(default=None)
    """
    Hardware model name of the phone.
    """

    name: typing.Optional[str] = pydantic.Field(default=None)
    """
    Optional user-chosen session label; unique among the org's active sessions.
    """

    nickname: typing.Optional[str] = pydantic.Field(default=None)
    """
    User-assigned phone nickname.
    """

    phone_id: str = pydantic.Field()
    """
    Phone the session ran on.
    """

    phone_name: typing.Optional[str] = pydantic.Field(default=None)
    """
    Display name of the phone.
    """

    phone_status: PhoneSessionDetailResponsePhoneStatus = pydantic.Field()
    """
    Fleet status of the phone.
    """

    phone_type: typing.Optional[PhoneSessionDetailResponsePhoneType] = pydantic.Field(default=None)
    """
    Platform of the phone.
    """

    recording_status: PhoneSessionDetailResponseRecordingStatus = pydantic.Field()
    """
    'ready' when the recording URL is present, 'pending' while the recording is still being processed, or 'expired' when it is past the plan's recording retention window.
    """

    recording_url: typing.Optional[str] = pydantic.Field(default=None)
    """
    Playback URL for the session recording, set only when ready.
    """

    session_id: str = pydantic.Field()
    """
    Session identifier.
    """

    source: PhoneSessionDetailResponseSource = pydantic.Field()
    """
    'workflow' when tied to a workflow, else 'interactive'.
    """

    status: PhoneSessionDetailResponseStatus = pydantic.Field()
    """
    Session lifecycle status.
    """

    tags: typing.Optional[typing.Dict[str, str]] = pydantic.Field(default=None)
    """
    Optional key->value labels attached to the session.
    """

    workflow_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    Workflow the session executed, when source is 'workflow'.
    """

    workflow_name: typing.Optional[str] = pydantic.Field(default=None)
    """
    Name of the workflow the session executed.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
