# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata


class PhoneSessionDetailResponse(UniversalBaseModel):
    schema_: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="$schema"),
        pydantic.Field(alias="$schema", description="A URL to the JSON Schema for this object."),
    ] = None
    allocated_at: str
    allocated_by: typing.Optional[str] = None
    deallocated_at: typing.Optional[str] = None
    is_dedicated_phone: bool
    location: typing.Optional[str] = None
    model_name: typing.Optional[str] = None
    nickname: typing.Optional[str] = None
    phone_id: str
    phone_name: typing.Optional[str] = None
    phone_status: str
    phone_type: typing.Optional[str] = None
    recording_status: str
    recording_url: typing.Optional[str] = None
    session_id: str
    source: str
    status: str
    workflow_id: typing.Optional[str] = None
    workflow_name: typing.Optional[str] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
