# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .phone_dedicated_availability import PhoneDedicatedAvailability
from .phone_shared_availability import PhoneSharedAvailability


class PhoneAvailabilityResponse(UniversalBaseModel):
    """
    Phone availability summary: shared-pool capacity plus the caller org's dedicated idle counts. An advisory snapshot - allocation is the authority and can still refuse.
    """

    schema_: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="$schema"),
        pydantic.Field(alias="$schema", description="A URL to the JSON Schema for this object."),
    ] = None
    dedicated: PhoneDedicatedAvailability = pydantic.Field()
    """
    The caller org's dedicated phones.
    """

    shared: PhoneSharedAvailability = pydantic.Field()
    """
    Shared-pool availability, fleet-wide.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
