# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .run_frame_status import RunFrameStatus


class RunSpanFrame(UniversalBaseModel):
    """
    One completed telemetry span in the canonical frame envelope.
    """

    attributes: typing.Optional[typing.Dict[str, typing.Any]] = pydantic.Field(default=None)
    """
    Every attribute the producer stamped (axilio.* vocabulary), verbatim. Attributes are the contract's extension seam: new keys appear here without a version bump.
    """

    end_time_unix_nano: typing.Optional[int] = pydantic.Field(default=None)
    """
    Span end, nanoseconds since the Unix epoch. Always set in the archive; omitted on the live stream's "start" phase, where the span is still in flight.
    """

    name: str = pydantic.Field()
    """
    Span name (for sdk_call spans, the SDK operation, e.g. Screen.observe).
    """

    parent_span_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    Parent span id; omitted on root spans.
    """

    phase: str = pydantic.Field()
    """
    Span phase. The archive returns completed spans only ("end"); "start" phases exist only on the live stream.
    """

    span_id: str = pydantic.Field()
    """
    OTel span id (16 lowercase hex chars). Upsert key: the live copy of this span carries the same id.
    """

    span_type: str = pydantic.Field()
    """
    Product span role: session (the session root), run, sdk_call, inference, file_push, media_capture. Spans stored before the 2026-08-21 vocabulary cutover carry the retired phone_session value for the session root. Unknown values MUST be rendered generically, never rejected.
    """

    start_time_unix_nano: int = pydantic.Field()
    """
    Span start, nanoseconds since the Unix epoch.
    """

    status: typing.Optional[RunFrameStatus] = pydantic.Field(default=None)
    """
    Span outcome. Always set in the archive; omitted on the live stream's "start" phase, where the span has no outcome yet.
    """

    trace_id: str = pydantic.Field()
    """
    OTel trace id (32 lowercase hex chars), derived from the session id: one session is one trace.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
