# This file was auto-generated by Fern from our API Definition.

import typing

RunResponseStatus = typing.Union[
    typing.Literal["scheduled", "queued", "running", "completed", "failed", "cancelled"], typing.Any
]
