# This file was auto-generated by Fern from our API Definition.

import typing

RunHistoryItemStatus = typing.Union[typing.Literal["queued", "running", "completed", "failed", "cancelled"], typing.Any]
