# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .run_history_item_status import RunHistoryItemStatus
from .run_history_item_trigger import RunHistoryItemTrigger


class RunHistoryItem(UniversalBaseModel):
    """
    A single historic run record.
    """

    canceled_at: typing.Optional[dt.datetime] = pydantic.Field(default=None)
    """
    Run cancellation time in UTC.
    """

    completed_at: typing.Optional[dt.datetime] = pydantic.Field(default=None)
    """
    Run completion time in UTC.
    """

    created_at: typing.Optional[dt.datetime] = pydantic.Field(default=None)
    """
    Run creation time in UTC.
    """

    error_message: typing.Optional[str] = pydantic.Field(default=None)
    """
    Error details if the run failed.
    """

    org_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    Organization that owns the run.
    """

    phone_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    Device that executed the run.
    """

    run_id: str = pydantic.Field()
    """
    Run identifier.
    """

    run_metadata: typing.Optional[str] = pydantic.Field(default=None)
    """
    Serialized arbitrary metadata for the run.
    """

    started_at: typing.Optional[dt.datetime] = pydantic.Field(default=None)
    """
    Run start time in UTC.
    """

    status: RunHistoryItemStatus = pydantic.Field()
    """
    Run's final status.
    """

    success: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Whether the run completed successfully.
    """

    trigger: RunHistoryItemTrigger = pydantic.Field()
    """
    Trigger identifies how the run was initiated.
    """

    user_id: str = pydantic.Field()
    """
    User who initiated the run.
    """

    video_url: typing.Optional[str] = pydantic.Field(default=None)
    """
    URL for the run recording video.
    """

    workflow_id: str = pydantic.Field()
    """
    Associated workflow identifier.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
