# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .run_frame_status import RunFrameStatus


class RunSessionFramesResponseFramesItem_Log(UniversalBaseModel):
    """
    One telemetry frame: a completed span or a log event, discriminated on kind. Tolerant reader (unified frame contract): consumers MUST ignore frames with an unknown kind, unknown fields within known kinds, and unknown span_type/log_type values (render generically, never error). Generated SDK types surface an unrecognized frame as an explicit UnknownFrame variant carrying the raw JSON, never a silent drop. A live-stream message MAY carry a JSON array of frame objects; consumers MUST accept a single object or an array.
    """

    kind: typing.Literal["log"] = "log"
    attributes: typing.Optional[typing.Dict[str, typing.Any]] = None
    body: str
    log_type: str
    severity: str
    span_id: typing.Optional[str] = None
    time_unix_nano: int
    trace_id: str

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class RunSessionFramesResponseFramesItem_Span(UniversalBaseModel):
    """
    One telemetry frame: a completed span or a log event, discriminated on kind. Tolerant reader (unified frame contract): consumers MUST ignore frames with an unknown kind, unknown fields within known kinds, and unknown span_type/log_type values (render generically, never error). Generated SDK types surface an unrecognized frame as an explicit UnknownFrame variant carrying the raw JSON, never a silent drop. A live-stream message MAY carry a JSON array of frame objects; consumers MUST accept a single object or an array.
    """

    kind: typing.Literal["span"] = "span"
    attributes: typing.Optional[typing.Dict[str, typing.Any]] = None
    end_time_unix_nano: typing.Optional[int] = None
    name: str
    parent_span_id: typing.Optional[str] = None
    phase: str
    span_id: str
    span_type: str
    start_time_unix_nano: int
    status: typing.Optional[RunFrameStatus] = None
    trace_id: str

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class RunSessionFramesResponseFramesItem_Unknown(UniversalBaseModel):
    """A future frame kind this SDK does not yet model.

    Extra fields retain the complete wire object. ``raw`` returns that object
    in its original semantic JSON shape for generic rendering or logging.
    """

    kind: pydantic.StrictStr

    if IS_PYDANTIC_V2:

        @pydantic.field_validator("kind")
        @classmethod
        def validate_unknown_kind(cls, value: str) -> str:
            if not value or value in {"log", "span"}:
                raise ValueError("unknown frame kind must be non-empty and not a known kind")
            return value

        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(
            extra="allow", frozen=True
        )  # type: ignore # Pydantic v2
    else:

        @pydantic.validator("kind")
        def validate_unknown_kind(cls, value: str) -> str:
            if not value or value in {"log", "span"}:
                raise ValueError("unknown frame kind must be non-empty and not a known kind")
            return value

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow

    @property
    def raw(self) -> typing.Dict[str, typing.Any]:
        if IS_PYDANTIC_V2:
            return typing.cast(typing.Dict[str, typing.Any], self.model_dump(by_alias=True))
        return typing.cast(typing.Dict[str, typing.Any], self.dict(by_alias=True))


RunSessionFramesResponseFramesItem = typing.Union[
    RunSessionFramesResponseFramesItem_Log,
    RunSessionFramesResponseFramesItem_Span,
    RunSessionFramesResponseFramesItem_Unknown,
]
