# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class UsageInferenceSortSpec(UniversalBaseModel):
    """
    One sort instruction for the inferences list.
    """

    field: str = pydantic.Field()
    """
    Column to sort by.
    """

    order: str = pydantic.Field()
    """
    Sort direction.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
