# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .usage_inference_endpoint import UsageInferenceEndpoint
from .usage_inference_ocr_engine import UsageInferenceOcrEngine


class UsageInference(UniversalBaseModel):
    """
    A single billed inference call.
    """

    api_key_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    API key that made the call.
    """

    cost_microdollars: int = pydantic.Field()
    """
    Final post-markup cost charged for this call.
    """

    created_at: dt.datetime = pydantic.Field()
    """
    Time the call completed, in UTC.
    """

    endpoint: UsageInferenceEndpoint = pydantic.Field()
    """
    Vision endpoint hit ('detect' or 'locate').
    """

    inference_id: str = pydantic.Field()
    """
    Unique inference-call identifier (inference_id).
    """

    latency_ms: int = pydantic.Field()
    """
    End-to-end call latency in milliseconds.
    """

    model: str = pydantic.Field()
    """
    Canonical provider/model identifier that served the call.
    """

    ocr_engine: typing.Optional[UsageInferenceOcrEngine] = pydantic.Field(default=None)
    """
    OCR engine used ('free' or 'premium'); empty for /locate.
    """

    ocr_pages: int = pydantic.Field()
    """
    Number of Textract pages billed (premium OCR only).
    """

    session_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    Device session this inference ran under, when driven by an allocation-scoped service token; empty for direct API-key calls.
    """

    vlm_model: typing.Optional[str] = pydantic.Field(default=None)
    """
    Semantic-find model used, when the call was a locate.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
