# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .webhook_endpoint_type import WebhookEndpointType


class WebhookEndpoint(UniversalBaseModel):
    """
    A registered webhook or BYOS endpoint.
    """

    schema_: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="$schema"),
        pydantic.Field(alias="$schema", description="A URL to the JSON Schema for this object."),
    ] = None
    config: typing.Optional[typing.Dict[str, str]] = pydantic.Field(default=None)
    """
    Non-secret configuration of a BYOS destination (e.g. queue_url + region). Absent for webhook destinations.
    """

    created_at: dt.datetime = pydantic.Field()
    """
    Timestamp when the endpoint was registered.
    """

    disabled: bool = pydantic.Field()
    """
    True once delivery has been suspended for a persistently failing endpoint.
    """

    event_types: typing.Optional[typing.List[str]] = pydantic.Field(default=None)
    """
    Subscribed event types ("*" means all).
    """

    id: str = pydantic.Field()
    """
    Endpoint identifier.
    """

    type: WebhookEndpointType = pydantic.Field()
    """
    Destination type: webhook or a BYOS type (aws_sqs, aws_s3, aws_kinesis).
    """

    url: typing.Optional[str] = pydantic.Field(default=None)
    """
    Delivery endpoint URL (webhook destinations).
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
