# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata


class WebhookDeliveryMetricPoint(UniversalBaseModel):
    """
    One aggregated bucket of delivery-attempt metrics.
    """

    avg_latency_ms: typing.Optional[float] = pydantic.Field(default=None)
    """
    Mean destination response time in the bucket, in milliseconds. Null when no attempt in the bucket recorded a latency.
    """

    endpoint_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    Destination this bucket aggregates. Empty when the series is not grouped by destination.
    """

    error_rate: float = pydantic.Field()
    """
    Failed over total in the bucket, from 0 to 1.
    """

    failed: int = pydantic.Field()
    """
    Failed-attempt count in the bucket.
    """

    p50latency_ms: typing_extensions.Annotated[
        typing.Optional[float],
        FieldMetadata(alias="p50_latency_ms"),
        pydantic.Field(
            alias="p50_latency_ms",
            description="Median destination response time in the bucket, in milliseconds. Null when no attempt recorded a latency.",
        ),
    ] = None
    p95latency_ms: typing_extensions.Annotated[
        typing.Optional[float],
        FieldMetadata(alias="p95_latency_ms"),
        pydantic.Field(
            alias="p95_latency_ms",
            description="95th-percentile destination response time in the bucket, in milliseconds. Null when no attempt recorded a latency.",
        ),
    ] = None
    p99latency_ms: typing_extensions.Annotated[
        typing.Optional[float],
        FieldMetadata(alias="p99_latency_ms"),
        pydantic.Field(
            alias="p99_latency_ms",
            description="99th-percentile destination response time in the bucket, in milliseconds. Null when no attempt recorded a latency.",
        ),
    ] = None
    time_bucket: typing.Optional[dt.datetime] = pydantic.Field(default=None)
    """
    Start of the time bucket. Null for a single aggregate over the whole window.
    """

    total: int = pydantic.Field()
    """
    Delivery-attempt count in the bucket.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
