# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .webhook_attempt_status import WebhookAttemptStatus


class WebhookAttempt(UniversalBaseModel):
    """
    One delivery attempt of an event to an endpoint.
    """

    attempt_number: int = pydantic.Field()
    """
    1-based position of this try among the event's tries to the endpoint: 1 is the first delivery, 2 and up are retries or replays.
    """

    delivered_at: typing.Optional[dt.datetime] = pydantic.Field(default=None)
    """
    Timestamp when the attempt completed, null if pending.
    """

    endpoint_id: str = pydantic.Field()
    """
    Endpoint the attempt targeted.
    """

    id: str = pydantic.Field()
    """
    Attempt identifier.
    """

    manual: bool = pydantic.Field()
    """
    True for an attempt driven by an explicit replay rather than the automatic retry schedule.
    """

    response_status: int = pydantic.Field()
    """
    HTTP status the endpoint returned, or 0 if it never answered.
    """

    status: WebhookAttemptStatus = pydantic.Field()
    """
    Attempt outcome: success (endpoint acknowledged with a 2xx) or failed (non-2xx or no answer).
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
