# This file was auto-generated by Fern from our API Definition.

import typing

WebhookEndpointCreateResponseType = typing.Union[
    typing.Literal["webhook", "aws_sqs", "aws_s3", "aws_kinesis"], typing.Any
]
