# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class WebhookDelivery(UniversalBaseModel):
    """
    One event in the delivery log.
    """

    endpoint_ids: typing.Optional[typing.List[str]] = pydantic.Field(default=None)
    """
    Endpoints the event was routed to: the subscribers of its type at publish time, or the one endpoint a targeted test named. Empty when none was subscribed.
    """

    event_id: str = pydantic.Field()
    """
    Event identifier.
    """

    event_type: str = pydantic.Field()
    """
    Event type the event was published to.
    """

    published_at: dt.datetime = pydantic.Field()
    """
    Timestamp when the event was published.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
