# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .webhook_delivery_metric_point import WebhookDeliveryMetricPoint


class WebhookDeliveryMetricsResponse(UniversalBaseModel):
    """
    Delivery-attempt metrics: volume, error rate and response time over the requested window.
    """

    schema_: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="$schema"),
        pydantic.Field(alias="$schema", description="A URL to the JSON Schema for this object."),
    ] = None
    points: typing.Optional[typing.List[WebhookDeliveryMetricPoint]] = pydantic.Field(default=None)
    """
    Aggregated metric buckets over the window.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
