# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class WorkflowWorkflowSummary(UniversalBaseModel):
    create_date: dt.datetime
    goal: str
    id: str
    last_run_at: typing.Optional[dt.datetime] = None
    name: str
    ocr_engine: str
    organization_id: typing.Optional[str] = None
    platform: str
    status: str
    update_date: dt.datetime
    user_id: str

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
