# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata


class WorkflowCreateResponse(UniversalBaseModel):
    """
    Returned after successfully creating a workflow.
    """

    schema_: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="$schema"),
        pydantic.Field(alias="$schema", description="A URL to the JSON Schema for this object."),
    ] = None
    revision: typing.Optional[int] = pydantic.Field(default=None)
    """
    Revision number of the first code revision (1), when code was provided.
    """

    revision_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    Id of the first code revision, when code was provided.
    """

    workflow_id: str = pydantic.Field()
    """
    Identifier assigned to the new workflow.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
