# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .tree_node_bounds import TreeNodeBounds


class AccessibilityTreeNode(UniversalBaseModel):
    """
    One accessibility tree node offered as a candidate target.

    Device-neutral: an Android AccessibilityNodeInfo, a browser AX node, a
    macOS AX element or a Windows UI Automation element all map onto it.
    `platform` carries native attributes the caller wants the model to see;
    it is opaque to argus and passed through to the model as given.
    """

    bounds: typing.Optional[TreeNodeBounds] = pydantic.Field(default=None)
    """
    Where the node is on screen
    """

    name: typing.Optional[str] = pydantic.Field(default=None)
    """
    Accessible name; empty when the node has none
    """

    node_id: str = pydantic.Field()
    """
    Caller's id for the node, unique in the request
    """

    platform: typing.Optional[typing.Dict[str, typing.Any]] = pydantic.Field(default=None)
    """
    Native attributes keyed by platform, passed through to the model
    """

    role: str = pydantic.Field()
    """
    Accessibility role, e.g. 'button', 'textbox'
    """

    value: typing.Optional[str] = pydantic.Field(default=None)
    """
    Current value (a text field's contents), when any
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
