# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .detection import Detection
from .hash_result import HashResult
from .inference_metadata import InferenceMetadata
from .ocr_result import OcrResult


class InferenceData(UniversalBaseModel):
    hash_result: typing.Optional[HashResult] = pydantic.Field(default=None)
    """
    Image hash of content area
    """

    icon_detections: typing.Optional[typing.List[Detection]] = pydantic.Field(default=None)
    """
    Icon detections (YOLO)
    """

    metadata: InferenceMetadata = pydantic.Field()
    """
    Inference metadata
    """

    ocr_results: typing.Optional[typing.List[OcrResult]] = pydantic.Field(default=None)
    """
    OCR text detections
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
