# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class TreeNodeBounds(UniversalBaseModel):
    """
    Pixel box of a tree node, top-left origin.

    In the screenshot's pixel space when the request carries one, else in the
    device's screen space. A collapsed node may have zero width or height.
    """

    height: int = pydantic.Field()
    """
    Height in pixels
    """

    width: int = pydantic.Field()
    """
    Width in pixels
    """

    x: int = pydantic.Field()
    """
    Left edge in pixels
    """

    y: int = pydantic.Field()
    """
    Top edge in pixels
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
